<?php
namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use AppBundle\Entity\Usuario;

/**
 * Class UsuarioLoadData
 * @package AppBundle\DataFixtures\ORM
 *
 * @author Roberto Zuñiga Araya <roberto.zuniga.araya@gmail.com>
 */
class LoadUsuarioData extends AbstractFixture implements OrderedFixtureInterface, ContainerAwareInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    /**
     * @param ContainerInterface|null $container
     */
    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $userManager = $this->container->get('fos_user.user_manager');

        /** @var Usuario $usuario1 */
        $usuario1111 = $userManager->createUser();

        $usuario1111->setUsername('roberto.zuniga.araya@gmail.com');
        $usuario1111->setNombres('Roberto Alfredo');
        $usuario1111->setApellidos('Zuñiga Araya');
        $usuario1111->setEmail('roberto.zuniga.araya@gmail.com');
        $usuario1111->setPlainPassword('123456');
        $usuario1111->setEnabled(true);
        $usuario1111->setRoles(array('ROLE_SUPER_ADMIN'));
        $userManager->updateUser($usuario1111, true);

        $this->addReference('usuario1111', $usuario1111);

        $usuario1= $userManager->createUser();$usuario1->setUsername('aaraya@imagina.cl'); $usuario1->setNombres('Ayllen'); $usuario1->setApellidos('Araya'); $usuario1->setEmail($usuario1->getUsername()); $usuario1->setPlainPassword('123456');$usuario1->setEnabled(true); $usuario1->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario1, true);$this->addReference('usuario1', $usuario1);
        $usuario2= $userManager->createUser();$usuario2->setUsername('acontreras@imagina.cl'); $usuario2->setNombres('Andres'); $usuario2->setApellidos('Contreras'); $usuario2->setEmail($usuario2->getUsername()); $usuario2->setPlainPassword('123456');$usuario2->setEnabled(true); $usuario2->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario2, true);$this->addReference('usuario2', $usuario2);
        $usuario3= $userManager->createUser();$usuario3->setUsername('acuadra@imagina.cl'); $usuario3->setNombres('Alejandra'); $usuario3->setApellidos('Cuadra'); $usuario3->setEmail($usuario3->getUsername()); $usuario3->setPlainPassword('123456');$usuario3->setEnabled(true); $usuario3->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario3, true);$this->addReference('usuario3', $usuario3);
        $usuario4= $userManager->createUser();$usuario4->setUsername('aduran@imagina.cl'); $usuario4->setNombres('Alberto'); $usuario4->setApellidos('Duran'); $usuario4->setEmail($usuario4->getUsername()); $usuario4->setPlainPassword('123456');$usuario4->setEnabled(true); $usuario4->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario4, true);$this->addReference('usuario4', $usuario4);
        $usuario5= $userManager->createUser();$usuario5->setUsername('aescobar@imagina.cl'); $usuario5->setNombres('Ana'); $usuario5->setApellidos('Escobar'); $usuario5->setEmail($usuario5->getUsername()); $usuario5->setPlainPassword('123456');$usuario5->setEnabled(true); $usuario5->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario5, true);$this->addReference('usuario5', $usuario5);
        $usuario6= $userManager->createUser();$usuario6->setUsername('afernandez@imagina.cl'); $usuario6->setNombres('Alejandra'); $usuario6->setApellidos('Fernandez'); $usuario6->setEmail($usuario6->getUsername()); $usuario6->setPlainPassword('123456');$usuario6->setEnabled(true); $usuario6->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario6, true);$this->addReference('usuario6', $usuario6);
        $usuario7= $userManager->createUser();$usuario7->setUsername('agonzalezm@imagina.cl'); $usuario7->setNombres('Alejandra'); $usuario7->setApellidos('Gonzalez Madrid'); $usuario7->setEmail($usuario7->getUsername()); $usuario7->setPlainPassword('123456');$usuario7->setEnabled(true); $usuario7->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario7, true);$this->addReference('usuario7', $usuario7);
        $usuario8= $userManager->createUser();$usuario8->setUsername('aindiveri@imagina.cl'); $usuario8->setNombres('Agustín'); $usuario8->setApellidos('Indiveri'); $usuario8->setEmail($usuario8->getUsername()); $usuario8->setPlainPassword('123456');$usuario8->setEnabled(true); $usuario8->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario8, true);$this->addReference('usuario8', $usuario8);
        $usuario9= $userManager->createUser();$usuario9->setUsername('alabarca@imagina.cl'); $usuario9->setNombres('Annie'); $usuario9->setApellidos('Labarca'); $usuario9->setEmail($usuario9->getUsername()); $usuario9->setPlainPassword('123456');$usuario9->setEnabled(true); $usuario9->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario9, true);$this->addReference('usuario9', $usuario9);
        $usuario10= $userManager->createUser();$usuario10->setUsername('allona@imagina.cl'); $usuario10->setNombres('Alejandra'); $usuario10->setApellidos('Llona'); $usuario10->setEmail($usuario10->getUsername()); $usuario10->setPlainPassword('123456');$usuario10->setEnabled(true); $usuario10->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario10, true);$this->addReference('usuario10', $usuario10);
        $usuario11= $userManager->createUser();$usuario11->setUsername('alopez@imagina.cl'); $usuario11->setNombres('Arturo'); $usuario11->setApellidos('Lopez'); $usuario11->setEmail($usuario11->getUsername()); $usuario11->setPlainPassword('123456');$usuario11->setEnabled(true); $usuario11->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario11, true);$this->addReference('usuario11', $usuario11);
        $usuario12= $userManager->createUser();$usuario12->setUsername('amocarquer@imagina.cl'); $usuario12->setNombres('Alejandra'); $usuario12->setApellidos('Mocarquer'); $usuario12->setEmail($usuario12->getUsername()); $usuario12->setPlainPassword('123456');$usuario12->setEnabled(true); $usuario12->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario12, true);$this->addReference('usuario12', $usuario12);
        $usuario13= $userManager->createUser();$usuario13->setUsername('amunoz@imagina.cl'); $usuario13->setNombres('Angelo'); $usuario13->setApellidos('Muñoz'); $usuario13->setEmail($usuario13->getUsername()); $usuario13->setPlainPassword('123456');$usuario13->setEnabled(true); $usuario13->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario13, true);$this->addReference('usuario13', $usuario13);
        $usuario14= $userManager->createUser();$usuario14->setUsername('aordenes@imagina.cl'); $usuario14->setNombres('Andrea'); $usuario14->setApellidos('Ordenes'); $usuario14->setEmail($usuario14->getUsername()); $usuario14->setPlainPassword('123456');$usuario14->setEnabled(true); $usuario14->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario14, true);$this->addReference('usuario14', $usuario14);
        $usuario15= $userManager->createUser();$usuario15->setUsername('arivera@imagina.cl'); $usuario15->setNombres('Anita'); $usuario15->setApellidos('Rivera Izam'); $usuario15->setEmail($usuario15->getUsername()); $usuario15->setPlainPassword('123456');$usuario15->setEnabled(true); $usuario15->setRoles(array('ROLE_ADMIN'));$userManager->updateUser($usuario15, true);$this->addReference('usuario15', $usuario15);
        $usuario16= $userManager->createUser();$usuario16->setUsername('arosales@imagina.cl'); $usuario16->setNombres('Ana Gabriela'); $usuario16->setApellidos('Rosales'); $usuario16->setEmail($usuario16->getUsername()); $usuario16->setPlainPassword('123456');$usuario16->setEnabled(true); $usuario16->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario16, true);$this->addReference('usuario16', $usuario16);
        $usuario17= $userManager->createUser();$usuario17->setUsername('aruiz@imagina.cl'); $usuario17->setNombres('Angel'); $usuario17->setApellidos('Ruiz'); $usuario17->setEmail($usuario17->getUsername()); $usuario17->setPlainPassword('123456');$usuario17->setEnabled(true); $usuario17->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario17, true);$this->addReference('usuario17', $usuario17);
        $usuario18= $userManager->createUser();$usuario18->setUsername('asandoval@imagina.cl'); $usuario18->setNombres('Alex'); $usuario18->setApellidos('Sandoval'); $usuario18->setEmail($usuario18->getUsername()); $usuario18->setPlainPassword('123456');$usuario18->setEnabled(true); $usuario18->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario18, true);$this->addReference('usuario18', $usuario18);
        $usuario19= $userManager->createUser();$usuario19->setUsername('asoto@imagina.cl'); $usuario19->setNombres('Andres'); $usuario19->setApellidos('Soto'); $usuario19->setEmail($usuario19->getUsername()); $usuario19->setPlainPassword('123456');$usuario19->setEnabled(true); $usuario19->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario19, true);$this->addReference('usuario19', $usuario19);
        $usuario20= $userManager->createUser();$usuario20->setUsername('avargas@imagina.cl'); $usuario20->setNombres('Ariel'); $usuario20->setApellidos('Vargas'); $usuario20->setEmail($usuario20->getUsername()); $usuario20->setPlainPassword('123456');$usuario20->setEnabled(true); $usuario20->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario20, true);$this->addReference('usuario20', $usuario20);
        $usuario21= $userManager->createUser();$usuario21->setUsername('avera@imagina.cl'); $usuario21->setNombres('Ana Maria'); $usuario21->setApellidos('Vera'); $usuario21->setEmail($usuario21->getUsername()); $usuario21->setPlainPassword('123456');$usuario21->setEnabled(true); $usuario21->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario21, true);$this->addReference('usuario21', $usuario21);
        $usuario22= $userManager->createUser();$usuario22->setUsername('bgonzalez@imagina.cl'); $usuario22->setNombres('Boniek'); $usuario22->setApellidos('Gonzalez'); $usuario22->setEmail($usuario22->getUsername()); $usuario22->setPlainPassword('123456');$usuario22->setEnabled(true); $usuario22->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario22, true);$this->addReference('usuario22', $usuario22);
        $usuario23= $userManager->createUser();$usuario23->setUsername('brodriguez@imagina.cl'); $usuario23->setNombres('Barbara'); $usuario23->setApellidos('Rodriguez'); $usuario23->setEmail($usuario23->getUsername()); $usuario23->setPlainPassword('123456');$usuario23->setEnabled(true); $usuario23->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario23, true);$this->addReference('usuario23', $usuario23);
        $usuario24= $userManager->createUser();$usuario24->setUsername('bsalazar@imagina.cl'); $usuario24->setNombres('Bernardita'); $usuario24->setApellidos('Salazar'); $usuario24->setEmail($usuario24->getUsername()); $usuario24->setPlainPassword('123456');$usuario24->setEnabled(true); $usuario24->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario24, true);$this->addReference('usuario24', $usuario24);
        $usuario25= $userManager->createUser();$usuario25->setUsername('cbarriga@imagina.cl'); $usuario25->setNombres('Cristian'); $usuario25->setApellidos('Barriga'); $usuario25->setEmail($usuario25->getUsername()); $usuario25->setPlainPassword('123456');$usuario25->setEnabled(true); $usuario25->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario25, true);$this->addReference('usuario25', $usuario25);
        $usuario26= $userManager->createUser();$usuario26->setUsername('cbarros@imagina.cl'); $usuario26->setNombres('Camila'); $usuario26->setApellidos('Barros'); $usuario26->setEmail($usuario26->getUsername()); $usuario26->setPlainPassword('123456');$usuario26->setEnabled(true); $usuario26->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario26, true);$this->addReference('usuario26', $usuario26);
        $usuario27= $userManager->createUser();$usuario27->setUsername('cbuchi@imagina.cl'); $usuario27->setNombres('Carolina'); $usuario27->setApellidos('Buchi Sagredo'); $usuario27->setEmail($usuario27->getUsername()); $usuario27->setPlainPassword('123456');$usuario27->setEnabled(true); $usuario27->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario27, true);$this->addReference('usuario27', $usuario27);
        $usuario28= $userManager->createUser();$usuario28->setUsername('ccampos@imagina.cl'); $usuario28->setNombres('Carolina'); $usuario28->setApellidos('Campos'); $usuario28->setEmail($usuario28->getUsername()); $usuario28->setPlainPassword('123456');$usuario28->setEnabled(true); $usuario28->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario28, true);$this->addReference('usuario28', $usuario28);
        $usuario29= $userManager->createUser();$usuario29->setUsername('ccastro@imagina.cl'); $usuario29->setNombres('Cristian'); $usuario29->setApellidos('Castro'); $usuario29->setEmail($usuario29->getUsername()); $usuario29->setPlainPassword('123456');$usuario29->setEnabled(true); $usuario29->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario29, true);$this->addReference('usuario29', $usuario29);
        $usuario30= $userManager->createUser();$usuario30->setUsername('ccutolo@imagina.cl'); $usuario30->setNombres('Claudia'); $usuario30->setApellidos('Cutolo'); $usuario30->setEmail($usuario30->getUsername()); $usuario30->setPlainPassword('123456');$usuario30->setEnabled(true); $usuario30->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario30, true);$this->addReference('usuario30', $usuario30);
        $usuario31= $userManager->createUser();$usuario31->setUsername('cdominguez@imagina.cl'); $usuario31->setNombres('Cristian'); $usuario31->setApellidos('Dominguez'); $usuario31->setEmail($usuario31->getUsername()); $usuario31->setPlainPassword('123456');$usuario31->setEnabled(true); $usuario31->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario31, true);$this->addReference('usuario31', $usuario31);
        $usuario32= $userManager->createUser();$usuario32->setUsername('cdonati@imagina.cl'); $usuario32->setNombres('Cristian'); $usuario32->setApellidos('Donati'); $usuario32->setEmail($usuario32->getUsername()); $usuario32->setPlainPassword('123456');$usuario32->setEnabled(true); $usuario32->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario32, true);$this->addReference('usuario32', $usuario32);
        $usuario33= $userManager->createUser();$usuario33->setUsername('cespinoza@imagina.cl'); $usuario33->setNombres('Carlos'); $usuario33->setApellidos('Espinoza'); $usuario33->setEmail($usuario33->getUsername()); $usuario33->setPlainPassword('123456');$usuario33->setEnabled(true); $usuario33->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario33, true);$this->addReference('usuario33', $usuario33);
        $usuario34= $userManager->createUser();$usuario34->setUsername('cespinozaa@imagina.cl'); $usuario34->setNombres('Claudia'); $usuario34->setApellidos('Espinoza'); $usuario34->setEmail($usuario34->getUsername()); $usuario34->setPlainPassword('123456');$usuario34->setEnabled(true); $usuario34->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario34, true);$this->addReference('usuario34', $usuario34);
        $usuario35= $userManager->createUser();$usuario35->setUsername('cfuentes@imagina.cl'); $usuario35->setNombres('Claudio'); $usuario35->setApellidos('Fuentes'); $usuario35->setEmail($usuario35->getUsername()); $usuario35->setPlainPassword('123456');$usuario35->setEnabled(true); $usuario35->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario35, true);$this->addReference('usuario35', $usuario35);
        $usuario36= $userManager->createUser();$usuario36->setUsername('cgaltermatt@imagina.cl'); $usuario36->setNombres('Carmen Gloria'); $usuario36->setApellidos('Altermatt'); $usuario36->setEmail($usuario36->getUsername()); $usuario36->setPlainPassword('123456');$usuario36->setEnabled(true); $usuario36->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario36, true);$this->addReference('usuario36', $usuario36);
        $usuario37= $userManager->createUser();$usuario37->setUsername('cgoldener@imagina.cl'); $usuario37->setNombres('Carla'); $usuario37->setApellidos('Goldener Garcia'); $usuario37->setEmail($usuario37->getUsername()); $usuario37->setPlainPassword('123456');$usuario37->setEnabled(true); $usuario37->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario37, true);$this->addReference('usuario37', $usuario37);
        $usuario38= $userManager->createUser();$usuario38->setUsername('cgomez@imagina.cl'); $usuario38->setNombres('Claudio'); $usuario38->setApellidos('Gomez'); $usuario38->setEmail($usuario38->getUsername()); $usuario38->setPlainPassword('123456');$usuario38->setEnabled(true); $usuario38->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario38, true);$this->addReference('usuario38', $usuario38);
        $usuario39= $userManager->createUser();$usuario39->setUsername('cgonzalez@imagina.cl'); $usuario39->setNombres('Carla'); $usuario39->setApellidos('Gonzalez'); $usuario39->setEmail($usuario39->getUsername()); $usuario39->setPlainPassword('123456');$usuario39->setEnabled(true); $usuario39->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario39, true);$this->addReference('usuario39', $usuario39);
        $usuario40= $userManager->createUser();$usuario40->setUsername('chernandez@imagina.cl'); $usuario40->setNombres('Cristian'); $usuario40->setApellidos('Hernandez'); $usuario40->setEmail($usuario40->getUsername()); $usuario40->setPlainPassword('123456');$usuario40->setEnabled(true); $usuario40->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario40, true);$this->addReference('usuario40', $usuario40);
        $usuario41= $userManager->createUser();$usuario41->setUsername('cherrera@imagina.cl'); $usuario41->setNombres('Carlos'); $usuario41->setApellidos('Herrera'); $usuario41->setEmail($usuario41->getUsername()); $usuario41->setPlainPassword('123456');$usuario41->setEnabled(true); $usuario41->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario41, true);$this->addReference('usuario41', $usuario41);
        $usuario42= $userManager->createUser();$usuario42->setUsername('clopez@imagina.cl'); $usuario42->setNombres('Cristian'); $usuario42->setApellidos('Lopez'); $usuario42->setEmail($usuario42->getUsername()); $usuario42->setPlainPassword('123456');$usuario42->setEnabled(true); $usuario42->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario42, true);$this->addReference('usuario42', $usuario42);
        $usuario43= $userManager->createUser();$usuario43->setUsername('cmunoz@imagina.cl'); $usuario43->setNombres('Claudia'); $usuario43->setApellidos('Muñoz'); $usuario43->setEmail($usuario43->getUsername()); $usuario43->setPlainPassword('123456');$usuario43->setEnabled(true); $usuario43->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario43, true);$this->addReference('usuario43', $usuario43);
        $usuario44= $userManager->createUser();$usuario44->setUsername('cnunez@imagina.cl'); $usuario44->setNombres('Carlos'); $usuario44->setApellidos('Nuñez'); $usuario44->setEmail($usuario44->getUsername()); $usuario44->setPlainPassword('123456');$usuario44->setEnabled(true); $usuario44->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario44, true);$this->addReference('usuario44', $usuario44);
        $usuario45= $userManager->createUser();$usuario45->setUsername('coliveros@imagina.cl'); $usuario45->setNombres('Carolina'); $usuario45->setApellidos('Oliveros'); $usuario45->setEmail($usuario45->getUsername()); $usuario45->setPlainPassword('123456');$usuario45->setEnabled(true); $usuario45->setRoles(array('ROLE_SUPER_ADMIN'));$userManager->updateUser($usuario45, true);$this->addReference('usuario45', $usuario45);
        $usuario46= $userManager->createUser();$usuario46->setUsername('corellana@imagina.cl'); $usuario46->setNombres('Claudio'); $usuario46->setApellidos('Orellana'); $usuario46->setEmail($usuario46->getUsername()); $usuario46->setPlainPassword('123456');$usuario46->setEnabled(true); $usuario46->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario46, true);$this->addReference('usuario46', $usuario46);
        $usuario47= $userManager->createUser();$usuario47->setUsername('cpinto@imagina.cl'); $usuario47->setNombres('Cristobal'); $usuario47->setApellidos('Pinto'); $usuario47->setEmail($usuario47->getUsername()); $usuario47->setPlainPassword('123456');$usuario47->setEnabled(true); $usuario47->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario47, true);$this->addReference('usuario47', $usuario47);
        $usuario48= $userManager->createUser();$usuario48->setUsername('csaavedra@imagina.cl'); $usuario48->setNombres('Camila'); $usuario48->setApellidos('Saavedra'); $usuario48->setEmail($usuario48->getUsername()); $usuario48->setPlainPassword('123456');$usuario48->setEnabled(true); $usuario48->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario48, true);$this->addReference('usuario48', $usuario48);
        $usuario49= $userManager->createUser();$usuario49->setUsername('ctapia@imagina.cl'); $usuario49->setNombres('Cecilia'); $usuario49->setApellidos('Tapia'); $usuario49->setEmail($usuario49->getUsername()); $usuario49->setPlainPassword('123456');$usuario49->setEnabled(true); $usuario49->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario49, true);$this->addReference('usuario49', $usuario49);
        $usuario50= $userManager->createUser();$usuario50->setUsername('cvera@imagina.cl'); $usuario50->setNombres('Cecilia'); $usuario50->setApellidos('Vera'); $usuario50->setEmail($usuario50->getUsername()); $usuario50->setPlainPassword('123456');$usuario50->setEnabled(true); $usuario50->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario50, true);$this->addReference('usuario50', $usuario50);
        $usuario51= $userManager->createUser();$usuario51->setUsername('cvergara@imagina.cl'); $usuario51->setNombres('Claudio'); $usuario51->setApellidos('Vergara'); $usuario51->setEmail($usuario51->getUsername()); $usuario51->setPlainPassword('123456');$usuario51->setEnabled(true); $usuario51->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario51, true);$this->addReference('usuario51', $usuario51);
        $usuario52= $userManager->createUser();$usuario52->setUsername('cvidal@imagina.cl'); $usuario52->setNombres('Camila'); $usuario52->setApellidos('Vidal'); $usuario52->setEmail($usuario52->getUsername()); $usuario52->setPlainPassword('123456');$usuario52->setEnabled(true); $usuario52->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario52, true);$this->addReference('usuario52', $usuario52);
        $usuario53= $userManager->createUser();$usuario53->setUsername('czambra@imagina.cl'); $usuario53->setNombres('Carolina'); $usuario53->setApellidos('Zambra'); $usuario53->setEmail($usuario53->getUsername()); $usuario53->setPlainPassword('123456');$usuario53->setEnabled(true); $usuario53->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario53, true);$this->addReference('usuario53', $usuario53);
        $usuario54= $userManager->createUser();$usuario54->setUsername('davalos@imagina.cl'); $usuario54->setNombres('Daniela'); $usuario54->setApellidos('Avalos'); $usuario54->setEmail($usuario54->getUsername()); $usuario54->setPlainPassword('123456');$usuario54->setEnabled(true); $usuario54->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario54, true);$this->addReference('usuario54', $usuario54);
        $usuario55= $userManager->createUser();$usuario55->setUsername('dbunzli@imagina.cl'); $usuario55->setNombres('Dominique'); $usuario55->setApellidos('Bunzli'); $usuario55->setEmail($usuario55->getUsername()); $usuario55->setPlainPassword('123456');$usuario55->setEnabled(true); $usuario55->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario55, true);$this->addReference('usuario55', $usuario55);
        $usuario56= $userManager->createUser();$usuario56->setUsername('dcerda@imagina.cl'); $usuario56->setNombres('Diego'); $usuario56->setApellidos('Cerda'); $usuario56->setEmail($usuario56->getUsername()); $usuario56->setPlainPassword('123456');$usuario56->setEnabled(true); $usuario56->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario56, true);$this->addReference('usuario56', $usuario56);
        $usuario57= $userManager->createUser();$usuario57->setUsername('dlipari@imagina.cl'); $usuario57->setNombres('Diego'); $usuario57->setApellidos('Lipari'); $usuario57->setEmail($usuario57->getUsername()); $usuario57->setPlainPassword('123456');$usuario57->setEnabled(true); $usuario57->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario57, true);$this->addReference('usuario57', $usuario57);
        $usuario58= $userManager->createUser();$usuario58->setUsername('dlobos@imagina.cl'); $usuario58->setNombres('Diego'); $usuario58->setApellidos('Lobos'); $usuario58->setEmail($usuario58->getUsername()); $usuario58->setPlainPassword('123456');$usuario58->setEnabled(true); $usuario58->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario58, true);$this->addReference('usuario58', $usuario58);
        $usuario59= $userManager->createUser();$usuario59->setUsername('dmorales@imagina.cl'); $usuario59->setNombres('Diego'); $usuario59->setApellidos('Morales'); $usuario59->setEmail($usuario59->getUsername()); $usuario59->setPlainPassword('123456');$usuario59->setEnabled(true); $usuario59->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario59, true);$this->addReference('usuario59', $usuario59);
        $usuario60= $userManager->createUser();$usuario60->setUsername('dmoya@imagina.cl'); $usuario60->setNombres('Daniella'); $usuario60->setApellidos('Moya'); $usuario60->setEmail($usuario60->getUsername()); $usuario60->setPlainPassword('123456');$usuario60->setEnabled(true); $usuario60->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario60, true);$this->addReference('usuario60', $usuario60);
        $usuario61= $userManager->createUser();$usuario61->setUsername('dnavarro@imagina.cl'); $usuario61->setNombres('Daniela'); $usuario61->setApellidos('Navarro'); $usuario61->setEmail($usuario61->getUsername()); $usuario61->setPlainPassword('123456');$usuario61->setEnabled(true); $usuario61->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario61, true);$this->addReference('usuario61', $usuario61);
        $usuario62= $userManager->createUser();$usuario62->setUsername('doyanedel@imagina.cl'); $usuario62->setNombres('Daniela'); $usuario62->setApellidos('Oyanedel'); $usuario62->setEmail($usuario62->getUsername()); $usuario62->setPlainPassword('123456');$usuario62->setEnabled(true); $usuario62->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario62, true);$this->addReference('usuario62', $usuario62);
        $usuario63= $userManager->createUser();$usuario63->setUsername('dponce@imagina.cl'); $usuario63->setNombres('Daniel'); $usuario63->setApellidos('Ponce'); $usuario63->setEmail($usuario63->getUsername()); $usuario63->setPlainPassword('123456');$usuario63->setEnabled(true); $usuario63->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario63, true);$this->addReference('usuario63', $usuario63);
        $usuario64= $userManager->createUser();$usuario64->setUsername('dramirez@imagina.cl'); $usuario64->setNombres('Denisse'); $usuario64->setApellidos('Ramírez'); $usuario64->setEmail($usuario64->getUsername()); $usuario64->setPlainPassword('123456');$usuario64->setEnabled(true); $usuario64->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario64, true);$this->addReference('usuario64', $usuario64);
        $usuario65= $userManager->createUser();$usuario65->setUsername('dreinoso@imagina.cl'); $usuario65->setNombres('David'); $usuario65->setApellidos('Reinoso'); $usuario65->setEmail($usuario65->getUsername()); $usuario65->setPlainPassword('123456');$usuario65->setEnabled(true); $usuario65->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario65, true);$this->addReference('usuario65', $usuario65);
        $usuario66= $userManager->createUser();$usuario66->setUsername('drodriguez@imagina.cl'); $usuario66->setNombres('Diego'); $usuario66->setApellidos('Rodriguez'); $usuario66->setEmail($usuario66->getUsername()); $usuario66->setPlainPassword('123456');$usuario66->setEnabled(true); $usuario66->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario66, true);$this->addReference('usuario66', $usuario66);
        $usuario67= $userManager->createUser();$usuario67->setUsername('druiz@imagina.cl'); $usuario67->setNombres('Doris'); $usuario67->setApellidos('Ruiz'); $usuario67->setEmail($usuario67->getUsername()); $usuario67->setPlainPassword('123456');$usuario67->setEnabled(true); $usuario67->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario67, true);$this->addReference('usuario67', $usuario67);
        $usuario68= $userManager->createUser();$usuario68->setUsername('eapablaza@imagina.cl'); $usuario68->setNombres('Elizabeth'); $usuario68->setApellidos('Apablaza'); $usuario68->setEmail($usuario68->getUsername()); $usuario68->setPlainPassword('123456');$usuario68->setEnabled(true); $usuario68->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario68, true);$this->addReference('usuario68', $usuario68);
        $usuario69= $userManager->createUser();$usuario69->setUsername('ecastillo@imagina.cl'); $usuario69->setNombres('Eduardo'); $usuario69->setApellidos('Castillo Aguilera'); $usuario69->setEmail($usuario69->getUsername()); $usuario69->setPlainPassword('123456');$usuario69->setEnabled(true); $usuario69->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario69, true);$this->addReference('usuario69', $usuario69);
        $usuario70= $userManager->createUser();$usuario70->setUsername('eespinoza@imagina.cl'); $usuario70->setNombres('Enrique'); $usuario70->setApellidos('Espinoza'); $usuario70->setEmail($usuario70->getUsername()); $usuario70->setPlainPassword('123456');$usuario70->setEnabled(true); $usuario70->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario70, true);$this->addReference('usuario70', $usuario70);
        $usuario71= $userManager->createUser();$usuario71->setUsername('efrias@imagina.cl'); $usuario71->setNombres('Eduardo'); $usuario71->setApellidos('Frias'); $usuario71->setEmail($usuario71->getUsername()); $usuario71->setPlainPassword('123456');$usuario71->setEnabled(true); $usuario71->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario71, true);$this->addReference('usuario71', $usuario71);
        $usuario72= $userManager->createUser();$usuario72->setUsername('efuentes@imagina.cl'); $usuario72->setNombres('Edgardo'); $usuario72->setApellidos('Fuentes'); $usuario72->setEmail($usuario72->getUsername()); $usuario72->setPlainPassword('123456');$usuario72->setEnabled(true); $usuario72->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario72, true);$this->addReference('usuario72', $usuario72);
        $usuario73= $userManager->createUser();$usuario73->setUsername('egaldames@imagina.cl'); $usuario73->setNombres('Evelyn'); $usuario73->setApellidos('Galdames'); $usuario73->setEmail($usuario73->getUsername()); $usuario73->setPlainPassword('123456');$usuario73->setEnabled(true); $usuario73->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario73, true);$this->addReference('usuario73', $usuario73);
        $usuario74= $userManager->createUser();$usuario74->setUsername('egonzalez@imagina.cl'); $usuario74->setNombres('Evelyn'); $usuario74->setApellidos('Gonzalez Santibanez'); $usuario74->setEmail($usuario74->getUsername()); $usuario74->setPlainPassword('123456');$usuario74->setEnabled(true); $usuario74->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario74, true);$this->addReference('usuario74', $usuario74);
        $usuario75= $userManager->createUser();$usuario75->setUsername('eossandon@imagina.cl'); $usuario75->setNombres('Esteban'); $usuario75->setApellidos('Ossandon'); $usuario75->setEmail($usuario75->getUsername()); $usuario75->setPlainPassword('123456');$usuario75->setEnabled(true); $usuario75->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario75, true);$this->addReference('usuario75', $usuario75);
        $usuario76= $userManager->createUser();$usuario76->setUsername('fcarreno@imagina.cl'); $usuario76->setNombres('Fabiola'); $usuario76->setApellidos('Carreño'); $usuario76->setEmail($usuario76->getUsername()); $usuario76->setPlainPassword('123456');$usuario76->setEnabled(true); $usuario76->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario76, true);$this->addReference('usuario76', $usuario76);
        $usuario77= $userManager->createUser();$usuario77->setUsername('fdiazm@imagina.cl'); $usuario77->setNombres('Freddy'); $usuario77->setApellidos('Diaz Morales'); $usuario77->setEmail($usuario77->getUsername()); $usuario77->setPlainPassword('123456');$usuario77->setEnabled(true); $usuario77->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario77, true);$this->addReference('usuario77', $usuario77);
        $usuario78= $userManager->createUser();$usuario78->setUsername('fgutierrez@imagina.cl'); $usuario78->setNombres('Felipe'); $usuario78->setApellidos('Gutierrez'); $usuario78->setEmail($usuario78->getUsername()); $usuario78->setPlainPassword('123456');$usuario78->setEnabled(true); $usuario78->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario78, true);$this->addReference('usuario78', $usuario78);
        $usuario79= $userManager->createUser();$usuario79->setUsername('flopez@imagina.cl'); $usuario79->setNombres('Francisco'); $usuario79->setApellidos('Lopez'); $usuario79->setEmail($usuario79->getUsername()); $usuario79->setPlainPassword('123456');$usuario79->setEnabled(true); $usuario79->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario79, true);$this->addReference('usuario79', $usuario79);
        $usuario80= $userManager->createUser();$usuario80->setUsername('fmontalvo@imagina.cl'); $usuario80->setNombres('Felipe'); $usuario80->setApellidos('Montalvo'); $usuario80->setEmail($usuario80->getUsername()); $usuario80->setPlainPassword('123456');$usuario80->setEnabled(true); $usuario80->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario80, true);$this->addReference('usuario80', $usuario80);
        $usuario81= $userManager->createUser();$usuario81->setUsername('fvasquez@imagina.cl'); $usuario81->setNombres('Francisco'); $usuario81->setApellidos('Vasquez'); $usuario81->setEmail($usuario81->getUsername()); $usuario81->setPlainPassword('123456');$usuario81->setEnabled(true); $usuario81->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario81, true);$this->addReference('usuario81', $usuario81);
        $usuario82= $userManager->createUser();$usuario82->setUsername('fvasquezv@imagina.cl'); $usuario82->setNombres('Felipe'); $usuario82->setApellidos('Vasquez'); $usuario82->setEmail($usuario82->getUsername()); $usuario82->setPlainPassword('123456');$usuario82->setEnabled(true); $usuario82->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario82, true);$this->addReference('usuario82', $usuario82);
        $usuario83= $userManager->createUser();$usuario83->setUsername('fvera@imagina.cl'); $usuario83->setNombres('Francisco'); $usuario83->setApellidos('Vera'); $usuario83->setEmail($usuario83->getUsername()); $usuario83->setPlainPassword('123456');$usuario83->setEnabled(true); $usuario83->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario83, true);$this->addReference('usuario83', $usuario83);
        $usuario84= $userManager->createUser();$usuario84->setUsername('gavila@imagina.cl'); $usuario84->setNombres('Genesis'); $usuario84->setApellidos('Avila'); $usuario84->setEmail($usuario84->getUsername()); $usuario84->setPlainPassword('123456');$usuario84->setEnabled(true); $usuario84->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario84, true);$this->addReference('usuario84', $usuario84);
        $usuario85= $userManager->createUser();$usuario85->setUsername('gbermudez@imagina.cl'); $usuario85->setNombres('Giancarlo'); $usuario85->setApellidos('Bermudez'); $usuario85->setEmail($usuario85->getUsername()); $usuario85->setPlainPassword('123456');$usuario85->setEnabled(true); $usuario85->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario85, true);$this->addReference('usuario85', $usuario85);
        $usuario86= $userManager->createUser();$usuario86->setUsername('gescon@imagina.cl'); $usuario86->setNombres('gescon'); $usuario86->setApellidos('imagina'); $usuario86->setEmail($usuario86->getUsername()); $usuario86->setPlainPassword('123456');$usuario86->setEnabled(true); $usuario86->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario86, true);$this->addReference('usuario86', $usuario86);
        $usuario87= $userManager->createUser();$usuario87->setUsername('gespinoza@imagina.cl'); $usuario87->setNombres('Guillermo'); $usuario87->setApellidos('Espinoza'); $usuario87->setEmail($usuario87->getUsername()); $usuario87->setPlainPassword('123456');$usuario87->setEnabled(true); $usuario87->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario87, true);$this->addReference('usuario87', $usuario87);
        $usuario88= $userManager->createUser();$usuario88->setUsername('ggonzalez@imagina.cl'); $usuario88->setNombres('Gino'); $usuario88->setApellidos('Gonzalez'); $usuario88->setEmail($usuario88->getUsername()); $usuario88->setPlainPassword('123456');$usuario88->setEnabled(true); $usuario88->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario88, true);$this->addReference('usuario88', $usuario88);
        $usuario89= $userManager->createUser();$usuario89->setUsername('harias@imagina.cl'); $usuario89->setNombres('Hugo'); $usuario89->setApellidos('Arias'); $usuario89->setEmail($usuario89->getUsername()); $usuario89->setPlainPassword('123456');$usuario89->setEnabled(true); $usuario89->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario89, true);$this->addReference('usuario89', $usuario89);
        $usuario90= $userManager->createUser();$usuario90->setUsername('hgonzalez@imagina.cl'); $usuario90->setNombres('Hugo'); $usuario90->setApellidos('Gonzalez'); $usuario90->setEmail($usuario90->getUsername()); $usuario90->setPlainPassword('123456');$usuario90->setEnabled(true); $usuario90->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario90, true);$this->addReference('usuario90', $usuario90);
        $usuario91= $userManager->createUser();$usuario91->setUsername('hjohnson@imagina.cl'); $usuario91->setNombres('Henry'); $usuario91->setApellidos('Johnson'); $usuario91->setEmail($usuario91->getUsername()); $usuario91->setPlainPassword('123456');$usuario91->setEnabled(true); $usuario91->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario91, true);$this->addReference('usuario91', $usuario91);
        $usuario92= $userManager->createUser();$usuario92->setUsername('hmarambio@imagina.cl'); $usuario92->setNombres('Hugo'); $usuario92->setApellidos('Marambio'); $usuario92->setEmail($usuario92->getUsername()); $usuario92->setPlainPassword('123456');$usuario92->setEnabled(true); $usuario92->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario92, true);$this->addReference('usuario92', $usuario92);
        $usuario93= $userManager->createUser();$usuario93->setUsername('hosorio@imagina.cl'); $usuario93->setNombres('Hector'); $usuario93->setApellidos('Osorio'); $usuario93->setEmail($usuario93->getUsername()); $usuario93->setPlainPassword('123456');$usuario93->setEnabled(true); $usuario93->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario93, true);$this->addReference('usuario93', $usuario93);
        $usuario94= $userManager->createUser();$usuario94->setUsername('hpequeno@imagina.cl'); $usuario94->setNombres('Hernan'); $usuario94->setApellidos('Pequeno'); $usuario94->setEmail($usuario94->getUsername()); $usuario94->setPlainPassword('123456');$usuario94->setEnabled(true); $usuario94->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario94, true);$this->addReference('usuario94', $usuario94);
        $usuario95= $userManager->createUser();$usuario95->setUsername('ibencomo@imagina.cl'); $usuario95->setNombres('Isabel'); $usuario95->setApellidos('Bencomo'); $usuario95->setEmail($usuario95->getUsername()); $usuario95->setPlainPassword('123456');$usuario95->setEnabled(true); $usuario95->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario95, true);$this->addReference('usuario95', $usuario95);
        $usuario96= $userManager->createUser();$usuario96->setUsername('icorellana@imagina.cl'); $usuario96->setNombres('Carolina'); $usuario96->setApellidos('Orellana'); $usuario96->setEmail($usuario96->getUsername()); $usuario96->setPlainPassword('123456');$usuario96->setEnabled(true); $usuario96->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario96, true);$this->addReference('usuario96', $usuario96);
        $usuario97= $userManager->createUser();$usuario97->setUsername('imoris@imagina.cl'); $usuario97->setNombres('Ian'); $usuario97->setApellidos('Moris'); $usuario97->setEmail($usuario97->getUsername()); $usuario97->setPlainPassword('123456');$usuario97->setEnabled(true); $usuario97->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario97, true);$this->addReference('usuario97', $usuario97);
        $usuario98= $userManager->createUser();$usuario98->setUsername('izuniga@imagina.cl'); $usuario98->setNombres('Irene'); $usuario98->setApellidos('Zuniga Rubilar'); $usuario98->setEmail($usuario98->getUsername()); $usuario98->setPlainPassword('123456');$usuario98->setEnabled(true); $usuario98->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario98, true);$this->addReference('usuario98', $usuario98);
        $usuario99= $userManager->createUser();$usuario99->setUsername('jabarzua@imagina.cl'); $usuario99->setNombres('Jorge'); $usuario99->setApellidos('Abarzúa C.'); $usuario99->setEmail($usuario99->getUsername()); $usuario99->setPlainPassword('123456');$usuario99->setEnabled(true); $usuario99->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario99, true);$this->addReference('usuario99', $usuario99);
        $usuario100= $userManager->createUser();$usuario100->setUsername('jaravena@imagina.cl'); $usuario100->setNombres('Juan Pablo'); $usuario100->setApellidos('Aravena'); $usuario100->setEmail($usuario100->getUsername()); $usuario100->setPlainPassword('123456');$usuario100->setEnabled(true); $usuario100->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario100, true);$this->addReference('usuario100', $usuario100);
        $usuario101= $userManager->createUser();$usuario101->setUsername('jcea@imagina.cl'); $usuario101->setNombres('José Luis'); $usuario101->setApellidos('Cea'); $usuario101->setEmail($usuario101->getUsername()); $usuario101->setPlainPassword('123456');$usuario101->setEnabled(true); $usuario101->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario101, true);$this->addReference('usuario101', $usuario101);
        $usuario102= $userManager->createUser();$usuario102->setUsername('jdominguez@imagina.cl'); $usuario102->setNombres('Jilberto'); $usuario102->setApellidos('Dominguez'); $usuario102->setEmail($usuario102->getUsername()); $usuario102->setPlainPassword('123456');$usuario102->setEnabled(true); $usuario102->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario102, true);$this->addReference('usuario102', $usuario102);
        $usuario103= $userManager->createUser();$usuario103->setUsername('jeyssautier@imagina.cl'); $usuario103->setNombres('Jean Paul'); $usuario103->setApellidos('Eyssautier'); $usuario103->setEmail($usuario103->getUsername()); $usuario103->setPlainPassword('123456');$usuario103->setEnabled(true); $usuario103->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario103, true);$this->addReference('usuario103', $usuario103);
        $usuario104= $userManager->createUser();$usuario104->setUsername('jhenriquez@imagina.cl'); $usuario104->setNombres('Javier'); $usuario104->setApellidos('Henriquez'); $usuario104->setEmail($usuario104->getUsername()); $usuario104->setPlainPassword('123456');$usuario104->setEnabled(true); $usuario104->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario104, true);$this->addReference('usuario104', $usuario104);
        $usuario105= $userManager->createUser();$usuario105->setUsername('jlizana@imagina.cl'); $usuario105->setNombres('Javier'); $usuario105->setApellidos('Lizana'); $usuario105->setEmail($usuario105->getUsername()); $usuario105->setPlainPassword('123456');$usuario105->setEnabled(true); $usuario105->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario105, true);$this->addReference('usuario105', $usuario105);
        $usuario106= $userManager->createUser();$usuario106->setUsername('jllancapan@imagina.cl'); $usuario106->setNombres('Judith'); $usuario106->setApellidos('Llancapan'); $usuario106->setEmail($usuario106->getUsername()); $usuario106->setPlainPassword('123456');$usuario106->setEnabled(true); $usuario106->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario106, true);$this->addReference('usuario106', $usuario106);
        $usuario107= $userManager->createUser();$usuario107->setUsername('jlmolina@imagina.cl'); $usuario107->setNombres('Jose Luis'); $usuario107->setApellidos('Molina'); $usuario107->setEmail($usuario107->getUsername()); $usuario107->setPlainPassword('123456');$usuario107->setEnabled(true); $usuario107->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario107, true);$this->addReference('usuario107', $usuario107);
        $usuario108= $userManager->createUser();$usuario108->setUsername('jlobo@imagina.cl'); $usuario108->setNombres('Juan'); $usuario108->setApellidos('Lobo'); $usuario108->setEmail($usuario108->getUsername()); $usuario108->setPlainPassword('123456');$usuario108->setEnabled(true); $usuario108->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario108, true);$this->addReference('usuario108', $usuario108);
        $usuario109= $userManager->createUser();$usuario109->setUsername('jlonnberg@imagina.cl'); $usuario109->setNombres('Jaime'); $usuario109->setApellidos('Lonnberg'); $usuario109->setEmail($usuario109->getUsername()); $usuario109->setPlainPassword('123456');$usuario109->setEnabled(true); $usuario109->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario109, true);$this->addReference('usuario109', $usuario109);
        $usuario110= $userManager->createUser();$usuario110->setUsername('jlopez@imagina.cl'); $usuario110->setNombres('Javier'); $usuario110->setApellidos('Lopez'); $usuario110->setEmail($usuario110->getUsername()); $usuario110->setPlainPassword('123456');$usuario110->setEnabled(true); $usuario110->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario110, true);$this->addReference('usuario110', $usuario110);
        $usuario111= $userManager->createUser();$usuario111->setUsername('jmlabra@imagina.cl'); $usuario111->setNombres('Juan'); $usuario111->setApellidos('Labra'); $usuario111->setEmail($usuario111->getUsername()); $usuario111->setPlainPassword('123456');$usuario111->setEnabled(true); $usuario111->setRoles(array('ROLE_SUPER_ADMIN'));$userManager->updateUser($usuario111, true);$this->addReference('usuario111', $usuario111);
        $usuario112= $userManager->createUser();$usuario112->setUsername('jmolina@imagina.cl'); $usuario112->setNombres('Juan Carlos'); $usuario112->setApellidos('Molina'); $usuario112->setEmail($usuario112->getUsername()); $usuario112->setPlainPassword('123456');$usuario112->setEnabled(true); $usuario112->setRoles(array('ROLE_SUPER_ADMIN'));$userManager->updateUser($usuario112, true);$this->addReference('usuario112', $usuario112);
        $usuario113= $userManager->createUser();$usuario113->setUsername('jmorales@imagina.cl'); $usuario113->setNombres('Jorge'); $usuario113->setApellidos('Morales'); $usuario113->setEmail($usuario113->getUsername()); $usuario113->setPlainPassword('123456');$usuario113->setEnabled(true); $usuario113->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario113, true);$this->addReference('usuario113', $usuario113);
        $usuario114= $userManager->createUser();$usuario114->setUsername('jmunoz@imagina.cl'); $usuario114->setNombres('Julio'); $usuario114->setApellidos('Muñoz'); $usuario114->setEmail($usuario114->getUsername()); $usuario114->setPlainPassword('123456');$usuario114->setEnabled(true); $usuario114->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario114, true);$this->addReference('usuario114', $usuario114);
        $usuario115= $userManager->createUser();$usuario115->setUsername('jolivares@imagina.cl'); $usuario115->setNombres('Jenniffer'); $usuario115->setApellidos('Olivares'); $usuario115->setEmail($usuario115->getUsername()); $usuario115->setPlainPassword('123456');$usuario115->setEnabled(true); $usuario115->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario115, true);$this->addReference('usuario115', $usuario115);
        $usuario116= $userManager->createUser();$usuario116->setUsername('jorjuela@imagina.cl'); $usuario116->setNombres('Jovanna'); $usuario116->setApellidos('Orjuela'); $usuario116->setEmail($usuario116->getUsername()); $usuario116->setPlainPassword('123456');$usuario116->setEnabled(true); $usuario116->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario116, true);$this->addReference('usuario116', $usuario116);
        $usuario117= $userManager->createUser();$usuario117->setUsername('jperezv@imagina.cl'); $usuario117->setNombres('Jean'); $usuario117->setApellidos('Perez'); $usuario117->setEmail($usuario117->getUsername()); $usuario117->setPlainPassword('123456');$usuario117->setEnabled(true); $usuario117->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario117, true);$this->addReference('usuario117', $usuario117);
        $usuario118= $userManager->createUser();$usuario118->setUsername('jpmeyerholz@imagina.cl'); $usuario118->setNombres('Juan Pablo'); $usuario118->setApellidos('Mayerho'); $usuario118->setEmail($usuario118->getUsername()); $usuario118->setPlainPassword('123456');$usuario118->setEnabled(true); $usuario118->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario118, true);$this->addReference('usuario118', $usuario118);
        $usuario119= $userManager->createUser();$usuario119->setUsername('jpulido@imagina.cl'); $usuario119->setNombres('Jose'); $usuario119->setApellidos('Pulido'); $usuario119->setEmail($usuario119->getUsername()); $usuario119->setPlainPassword('123456');$usuario119->setEnabled(true); $usuario119->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario119, true);$this->addReference('usuario119', $usuario119);
        $usuario120= $userManager->createUser();$usuario120->setUsername('jrojas@imagina.cl'); $usuario120->setNombres('Jacqueline'); $usuario120->setApellidos('Rojas'); $usuario120->setEmail($usuario120->getUsername()); $usuario120->setPlainPassword('123456');$usuario120->setEnabled(true); $usuario120->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario120, true);$this->addReference('usuario120', $usuario120);
        $usuario121= $userManager->createUser();$usuario121->setUsername('jsaez@imagina.cl'); $usuario121->setNombres('Jose'); $usuario121->setApellidos('Saez'); $usuario121->setEmail($usuario121->getUsername()); $usuario121->setPlainPassword('123456');$usuario121->setEnabled(true); $usuario121->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario121, true);$this->addReference('usuario121', $usuario121);
        $usuario122= $userManager->createUser();$usuario122->setUsername('jsanchez@imagina.cl'); $usuario122->setNombres('Javiera'); $usuario122->setApellidos('Sanchez'); $usuario122->setEmail($usuario122->getUsername()); $usuario122->setPlainPassword('123456');$usuario122->setEnabled(true); $usuario122->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario122, true);$this->addReference('usuario122', $usuario122);
        $usuario123= $userManager->createUser();$usuario123->setUsername('jtapia@imagina.cl'); $usuario123->setNombres('Javier'); $usuario123->setApellidos('Tapia'); $usuario123->setEmail($usuario123->getUsername()); $usuario123->setPlainPassword('123456');$usuario123->setEnabled(true); $usuario123->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario123, true);$this->addReference('usuario123', $usuario123);
        $usuario124= $userManager->createUser();$usuario124->setUsername('jvargas@imagina.cl'); $usuario124->setNombres('Juan Pablo'); $usuario124->setApellidos('Vargas'); $usuario124->setEmail($usuario124->getUsername()); $usuario124->setPlainPassword('123456');$usuario124->setEnabled(true); $usuario124->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario124, true);$this->addReference('usuario124', $usuario124);
        $usuario125= $userManager->createUser();$usuario125->setUsername('jvega@imagina.cl'); $usuario125->setNombres('Juan Pablo'); $usuario125->setApellidos('Vega'); $usuario125->setEmail($usuario125->getUsername()); $usuario125->setPlainPassword('123456');$usuario125->setEnabled(true); $usuario125->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario125, true);$this->addReference('usuario125', $usuario125);
        $usuario126= $userManager->createUser();$usuario126->setUsername('jvergara@imagina.cl'); $usuario126->setNombres('Jose Antonio'); $usuario126->setApellidos('Vergara'); $usuario126->setEmail($usuario126->getUsername()); $usuario126->setPlainPassword('123456');$usuario126->setEnabled(true); $usuario126->setRoles(array('ROLE_ADMIN'));$userManager->updateUser($usuario126, true);$this->addReference('usuario126', $usuario126);
        $usuario127= $userManager->createUser();$usuario127->setUsername('jvidela@imagina.cl'); $usuario127->setNombres('Jonathan'); $usuario127->setApellidos('Videla'); $usuario127->setEmail($usuario127->getUsername()); $usuario127->setPlainPassword('123456');$usuario127->setEnabled(true); $usuario127->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario127, true);$this->addReference('usuario127', $usuario127);
        $usuario128= $userManager->createUser();$usuario128->setUsername('jvoigt@imagina.cl'); $usuario128->setNombres('Jorge'); $usuario128->setApellidos('Voigt'); $usuario128->setEmail($usuario128->getUsername()); $usuario128->setPlainPassword('123456');$usuario128->setEnabled(true); $usuario128->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario128, true);$this->addReference('usuario128', $usuario128);
        $usuario129= $userManager->createUser();$usuario129->setUsername('kastudillo@imagina.cl'); $usuario129->setNombres('Karina'); $usuario129->setApellidos('Astudillo'); $usuario129->setEmail($usuario129->getUsername()); $usuario129->setPlainPassword('123456');$usuario129->setEnabled(true); $usuario129->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario129, true);$this->addReference('usuario129', $usuario129);
        $usuario130= $userManager->createUser();$usuario130->setUsername('kflandez@imagina.cl'); $usuario130->setNombres('Karina'); $usuario130->setApellidos('Flandez'); $usuario130->setEmail($usuario130->getUsername()); $usuario130->setPlainPassword('123456');$usuario130->setEnabled(true); $usuario130->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario130, true);$this->addReference('usuario130', $usuario130);
        $usuario131= $userManager->createUser();$usuario131->setUsername('kgonzalez@imagina.cl'); $usuario131->setNombres('Katherine'); $usuario131->setApellidos('González'); $usuario131->setEmail($usuario131->getUsername()); $usuario131->setPlainPassword('123456');$usuario131->setEnabled(true); $usuario131->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario131, true);$this->addReference('usuario131', $usuario131);
        $usuario132= $userManager->createUser();$usuario132->setUsername('lfuenzalida@imagina.cl'); $usuario132->setNombres('Lency'); $usuario132->setApellidos('Fuenzalida'); $usuario132->setEmail($usuario132->getUsername()); $usuario132->setPlainPassword('123456');$usuario132->setEnabled(true); $usuario132->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario132, true);$this->addReference('usuario132', $usuario132);
        $usuario133= $userManager->createUser();$usuario133->setUsername('ljara@imagina.cl'); $usuario133->setNombres('Lisbeth'); $usuario133->setApellidos('Jara'); $usuario133->setEmail($usuario133->getUsername()); $usuario133->setPlainPassword('123456');$usuario133->setEnabled(true); $usuario133->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario133, true);$this->addReference('usuario133', $usuario133);
        $usuario134= $userManager->createUser();$usuario134->setUsername('lroa@imagina.cl'); $usuario134->setNombres('Luis'); $usuario134->setApellidos('Roa'); $usuario134->setEmail($usuario134->getUsername()); $usuario134->setPlainPassword('123456');$usuario134->setEnabled(true); $usuario134->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario134, true);$this->addReference('usuario134', $usuario134);
        $usuario135= $userManager->createUser();$usuario135->setUsername('lrodriguez@imagina.cl'); $usuario135->setNombres('Leonardo'); $usuario135->setApellidos('Rodriguez'); $usuario135->setEmail($usuario135->getUsername()); $usuario135->setPlainPassword('123456');$usuario135->setEnabled(true); $usuario135->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario135, true);$this->addReference('usuario135', $usuario135);
        $usuario136= $userManager->createUser();$usuario136->setUsername('lsanjuan@imagina.cl'); $usuario136->setNombres('Luis'); $usuario136->setApellidos('San Juan'); $usuario136->setEmail($usuario136->getUsername()); $usuario136->setPlainPassword('123456');$usuario136->setEnabled(true); $usuario136->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario136, true);$this->addReference('usuario136', $usuario136);
        $usuario137= $userManager->createUser();$usuario137->setUsername('lvasquez@imagina.cl'); $usuario137->setNombres('Liliana'); $usuario137->setApellidos('Vásquez'); $usuario137->setEmail($usuario137->getUsername()); $usuario137->setPlainPassword('123456');$usuario137->setEnabled(true); $usuario137->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario137, true);$this->addReference('usuario137', $usuario137);
        $usuario138= $userManager->createUser();$usuario138->setUsername('magodoy@imagina.cl'); $usuario138->setNombres('Maria Angelica'); $usuario138->setApellidos('Godoy'); $usuario138->setEmail($usuario138->getUsername()); $usuario138->setPlainPassword('123456');$usuario138->setEnabled(true); $usuario138->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario138, true);$this->addReference('usuario138', $usuario138);
        $usuario139= $userManager->createUser();$usuario139->setUsername('maortiz@imagina.cl'); $usuario139->setNombres('Miguel Angel'); $usuario139->setApellidos('Ortiz'); $usuario139->setEmail($usuario139->getUsername()); $usuario139->setPlainPassword('123456');$usuario139->setEnabled(true); $usuario139->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario139, true);$this->addReference('usuario139', $usuario139);
        $usuario140= $userManager->createUser();$usuario140->setUsername('mbermeosolo@imagina.cl'); $usuario140->setNombres('Maria'); $usuario140->setApellidos('Bermeosolo'); $usuario140->setEmail($usuario140->getUsername()); $usuario140->setPlainPassword('123456');$usuario140->setEnabled(true); $usuario140->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario140, true);$this->addReference('usuario140', $usuario140);
        $usuario141= $userManager->createUser();$usuario141->setUsername('mbermudez@imagina.cl'); $usuario141->setNombres('Mairim'); $usuario141->setApellidos('Bermudez'); $usuario141->setEmail($usuario141->getUsername()); $usuario141->setPlainPassword('123456');$usuario141->setEnabled(true); $usuario141->setRoles(array('ROLE_SUPER_ADMIN'));$userManager->updateUser($usuario141, true);$this->addReference('usuario141', $usuario141);
        $usuario142= $userManager->createUser();$usuario142->setUsername('mbustos@imagina.cl'); $usuario142->setNombres('Mauricio'); $usuario142->setApellidos('Bustos'); $usuario142->setEmail($usuario142->getUsername()); $usuario142->setPlainPassword('123456');$usuario142->setEnabled(true); $usuario142->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario142, true);$this->addReference('usuario142', $usuario142);
        $usuario143= $userManager->createUser();$usuario143->setUsername('mcarcamo@imagina.cl'); $usuario143->setNombres('Mauricio'); $usuario143->setApellidos('Carcamo'); $usuario143->setEmail($usuario143->getUsername()); $usuario143->setPlainPassword('123456');$usuario143->setEnabled(true); $usuario143->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario143, true);$this->addReference('usuario143', $usuario143);
        $usuario144= $userManager->createUser();$usuario144->setUsername('mcastro@imagina.cl'); $usuario144->setNombres('Maria Fernanda'); $usuario144->setApellidos('Castro'); $usuario144->setEmail($usuario144->getUsername()); $usuario144->setPlainPassword('123456');$usuario144->setEnabled(true); $usuario144->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario144, true);$this->addReference('usuario144', $usuario144);
        $usuario145= $userManager->createUser();$usuario145->setUsername('mfarias@imagina.cl'); $usuario145->setNombres('Marcelo'); $usuario145->setApellidos('Farias'); $usuario145->setEmail($usuario145->getUsername()); $usuario145->setPlainPassword('123456');$usuario145->setEnabled(true); $usuario145->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario145, true);$this->addReference('usuario145', $usuario145);
        $usuario146= $userManager->createUser();$usuario146->setUsername('mgajardo@imagina.cl'); $usuario146->setNombres('Mauricio'); $usuario146->setApellidos('Gajardo'); $usuario146->setEmail($usuario146->getUsername()); $usuario146->setPlainPassword('123456');$usuario146->setEnabled(true); $usuario146->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario146, true);$this->addReference('usuario146', $usuario146);
        $usuario147= $userManager->createUser();$usuario147->setUsername('mgodoy@imagina.cl'); $usuario147->setNombres('Mariela'); $usuario147->setApellidos('Godoy'); $usuario147->setEmail($usuario147->getUsername()); $usuario147->setPlainPassword('123456');$usuario147->setEnabled(true); $usuario147->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario147, true);$this->addReference('usuario147', $usuario147);
        $usuario148= $userManager->createUser();$usuario148->setUsername('mgonzalez@imagina.cl'); $usuario148->setNombres('Maricel'); $usuario148->setApellidos('Gonzalez'); $usuario148->setEmail($usuario148->getUsername()); $usuario148->setPlainPassword('123456');$usuario148->setEnabled(true); $usuario148->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario148, true);$this->addReference('usuario148', $usuario148);
        $usuario149= $userManager->createUser();$usuario149->setUsername('micalderon@imagina.cl'); $usuario149->setNombres('Michel'); $usuario149->setApellidos('Calderon'); $usuario149->setEmail($usuario149->getUsername()); $usuario149->setPlainPassword('123456');$usuario149->setEnabled(true); $usuario149->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario149, true);$this->addReference('usuario149', $usuario149);
        $usuario150= $userManager->createUser();$usuario150->setUsername('mjaque@imagina.cl'); $usuario150->setNombres('María Elena'); $usuario150->setApellidos('Jaque'); $usuario150->setEmail($usuario150->getUsername()); $usuario150->setPlainPassword('123456');$usuario150->setEnabled(true); $usuario150->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario150, true);$this->addReference('usuario150', $usuario150);
        $usuario151= $userManager->createUser();$usuario151->setUsername('mlopez@imagina.cl'); $usuario151->setNombres('Marcela'); $usuario151->setApellidos('Lopez larenas'); $usuario151->setEmail($usuario151->getUsername()); $usuario151->setPlainPassword('123456');$usuario151->setEnabled(true); $usuario151->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario151, true);$this->addReference('usuario151', $usuario151);
        $usuario152= $userManager->createUser();$usuario152->setUsername('mnavarro@imagina.cl'); $usuario152->setNombres('Marta'); $usuario152->setApellidos('Navarro'); $usuario152->setEmail($usuario152->getUsername()); $usuario152->setPlainPassword('123456');$usuario152->setEnabled(true); $usuario152->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario152, true);$this->addReference('usuario152', $usuario152);
        $usuario153= $userManager->createUser();$usuario153->setUsername('mperello@imagina.cl'); $usuario153->setNombres('Mauricio'); $usuario153->setApellidos('Perello Duran'); $usuario153->setEmail($usuario153->getUsername()); $usuario153->setPlainPassword('123456');$usuario153->setEnabled(true); $usuario153->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario153, true);$this->addReference('usuario153', $usuario153);
        $usuario154= $userManager->createUser();$usuario154->setUsername('mrodriguez@imagina.cl'); $usuario154->setNombres('Marcelo'); $usuario154->setApellidos('Rodriguez'); $usuario154->setEmail($usuario154->getUsername()); $usuario154->setPlainPassword('123456');$usuario154->setEnabled(true); $usuario154->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario154, true);$this->addReference('usuario154', $usuario154);
        $usuario155= $userManager->createUser();$usuario155->setUsername('mtolosa@imagina.cl'); $usuario155->setNombres('Mauricio'); $usuario155->setApellidos('Tolosa'); $usuario155->setEmail($usuario155->getUsername()); $usuario155->setPlainPassword('123456');$usuario155->setEnabled(true); $usuario155->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario155, true);$this->addReference('usuario155', $usuario155);
        $usuario156= $userManager->createUser();$usuario156->setUsername('mvfuenzalida@imagina.cl'); $usuario156->setNombres('Maria Victoria'); $usuario156->setApellidos('Fuenzalida Petermann'); $usuario156->setEmail($usuario156->getUsername()); $usuario156->setPlainPassword('123456');$usuario156->setEnabled(true); $usuario156->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario156, true);$this->addReference('usuario156', $usuario156);
        $usuario157= $userManager->createUser();$usuario157->setUsername('ndiazv@imagina.cl'); $usuario157->setNombres('Nicol'); $usuario157->setApellidos('Díaz'); $usuario157->setEmail($usuario157->getUsername()); $usuario157->setPlainPassword('123456');$usuario157->setEnabled(true); $usuario157->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario157, true);$this->addReference('usuario157', $usuario157);
        $usuario158= $userManager->createUser();$usuario158->setUsername('ngonzalez@imagina.cl'); $usuario158->setNombres('Noemi'); $usuario158->setApellidos('Gonzalez'); $usuario158->setEmail($usuario158->getUsername()); $usuario158->setPlainPassword('123456');$usuario158->setEnabled(true); $usuario158->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario158, true);$this->addReference('usuario158', $usuario158);
        $usuario159= $userManager->createUser();$usuario159->setUsername('ngonzalezv@imagina.cl'); $usuario159->setNombres('Norma'); $usuario159->setApellidos('Gonzalez Vejar'); $usuario159->setEmail($usuario159->getUsername()); $usuario159->setPlainPassword('123456');$usuario159->setEnabled(true); $usuario159->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario159, true);$this->addReference('usuario159', $usuario159);
        $usuario160= $userManager->createUser();$usuario160->setUsername('nmunoz@imagina.cl'); $usuario160->setNombres('Nathalie'); $usuario160->setApellidos('Muñoz'); $usuario160->setEmail($usuario160->getUsername()); $usuario160->setPlainPassword('123456');$usuario160->setEnabled(true); $usuario160->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario160, true);$this->addReference('usuario160', $usuario160);
        $usuario161= $userManager->createUser();$usuario161->setUsername('nparra@imagina.cl'); $usuario161->setNombres('Natalia'); $usuario161->setApellidos('Parra'); $usuario161->setEmail($usuario161->getUsername()); $usuario161->setPlainPassword('123456');$usuario161->setEnabled(true); $usuario161->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario161, true);$this->addReference('usuario161', $usuario161);
        $usuario162= $userManager->createUser();$usuario162->setUsername('pespinoza@imagina.cl'); $usuario162->setNombres('Patricia'); $usuario162->setApellidos('Espinoza'); $usuario162->setEmail($usuario162->getUsername()); $usuario162->setPlainPassword('123456');$usuario162->setEnabled(true); $usuario162->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario162, true);$this->addReference('usuario162', $usuario162);
        $usuario163= $userManager->createUser();$usuario163->setUsername('phernandez@imagina.cl'); $usuario163->setNombres('Paulina'); $usuario163->setApellidos('Hernandez'); $usuario163->setEmail($usuario163->getUsername()); $usuario163->setPlainPassword('123456');$usuario163->setEnabled(true); $usuario163->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario163, true);$this->addReference('usuario163', $usuario163);
        $usuario164= $userManager->createUser();$usuario164->setUsername('pmiranda@imagina.cl'); $usuario164->setNombres('Paola'); $usuario164->setApellidos('Miranda'); $usuario164->setEmail($usuario164->getUsername()); $usuario164->setPlainPassword('123456');$usuario164->setEnabled(true); $usuario164->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario164, true);$this->addReference('usuario164', $usuario164);
        $usuario165= $userManager->createUser();$usuario165->setUsername('pnavarro@imagina.cl'); $usuario165->setNombres('Patricio'); $usuario165->setApellidos('Navarro'); $usuario165->setEmail($usuario165->getUsername()); $usuario165->setPlainPassword('123456');$usuario165->setEnabled(true); $usuario165->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario165, true);$this->addReference('usuario165', $usuario165);
        $usuario166= $userManager->createUser();$usuario166->setUsername('polivares@imagina.cl'); $usuario166->setNombres('Pia'); $usuario166->setApellidos('Olivares'); $usuario166->setEmail($usuario166->getUsername()); $usuario166->setPlainPassword('123456');$usuario166->setEnabled(true); $usuario166->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario166, true);$this->addReference('usuario166', $usuario166);
        $usuario167= $userManager->createUser();$usuario167->setUsername('psalinaso@imagina.cl'); $usuario167->setNombres('Patricio'); $usuario167->setApellidos('Salinas Ortiz'); $usuario167->setEmail($usuario167->getUsername()); $usuario167->setPlainPassword('123456');$usuario167->setEnabled(true); $usuario167->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario167, true);$this->addReference('usuario167', $usuario167);
        $usuario168= $userManager->createUser();$usuario168->setUsername('pvidal@imagina.cl'); $usuario168->setNombres('Paz'); $usuario168->setApellidos('Vidal'); $usuario168->setEmail($usuario168->getUsername()); $usuario168->setPlainPassword('123456');$usuario168->setEnabled(true); $usuario168->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario168, true);$this->addReference('usuario168', $usuario168);
        $usuario169= $userManager->createUser();$usuario169->setUsername('rbernal@imagina.cl'); $usuario169->setNombres('Raul'); $usuario169->setApellidos('Bernal'); $usuario169->setEmail($usuario169->getUsername()); $usuario169->setPlainPassword('123456');$usuario169->setEnabled(true); $usuario169->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario169, true);$this->addReference('usuario169', $usuario169);
        $usuario170= $userManager->createUser();$usuario170->setUsername('rbriones@imagina.cl'); $usuario170->setNombres('Rafael'); $usuario170->setApellidos('Briones'); $usuario170->setEmail($usuario170->getUsername()); $usuario170->setPlainPassword('123456');$usuario170->setEnabled(true); $usuario170->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario170, true);$this->addReference('usuario170', $usuario170);
        $usuario171= $userManager->createUser();$usuario171->setUsername('rcofre@imagina.cl'); $usuario171->setNombres('Rodrigo'); $usuario171->setApellidos('Cofre'); $usuario171->setEmail($usuario171->getUsername()); $usuario171->setPlainPassword('123456');$usuario171->setEnabled(true); $usuario171->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario171, true);$this->addReference('usuario171', $usuario171);
        $usuario172= $userManager->createUser();$usuario172->setUsername('rcornejo@imagina.cl'); $usuario172->setNombres('Roberto'); $usuario172->setApellidos('Cornejo'); $usuario172->setEmail($usuario172->getUsername()); $usuario172->setPlainPassword('123456');$usuario172->setEnabled(true); $usuario172->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario172, true);$this->addReference('usuario172', $usuario172);
        $usuario173= $userManager->createUser();$usuario173->setUsername('rgonzalez@imagina.cl'); $usuario173->setNombres('Rodrigo'); $usuario173->setApellidos('González'); $usuario173->setEmail($usuario173->getUsername()); $usuario173->setPlainPassword('123456');$usuario173->setEnabled(true); $usuario173->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario173, true);$this->addReference('usuario173', $usuario173);
        $usuario174= $userManager->createUser();$usuario174->setUsername('rmaguilera@imagina.cl'); $usuario174->setNombres('Rogelio'); $usuario174->setApellidos('Aguilera Araya'); $usuario174->setEmail($usuario174->getUsername()); $usuario174->setPlainPassword('123456');$usuario174->setEnabled(true); $usuario174->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario174, true);$this->addReference('usuario174', $usuario174);
        $usuario175= $userManager->createUser();$usuario175->setUsername('rmayorca@imagina.cl'); $usuario175->setNombres('Rebeca'); $usuario175->setApellidos('Mayorca'); $usuario175->setEmail($usuario175->getUsername()); $usuario175->setPlainPassword('123456');$usuario175->setEnabled(true); $usuario175->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario175, true);$this->addReference('usuario175', $usuario175);
        $usuario176= $userManager->createUser();$usuario176->setUsername('rmunoz@imagina.cl'); $usuario176->setNombres('Roberto'); $usuario176->setApellidos('Muñoz'); $usuario176->setEmail($usuario176->getUsername()); $usuario176->setPlainPassword('123456');$usuario176->setEnabled(true); $usuario176->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario176, true);$this->addReference('usuario176', $usuario176);
        $usuario177= $userManager->createUser();$usuario177->setUsername('rneira@imagina.cl'); $usuario177->setNombres('Rodrigo'); $usuario177->setApellidos('Neira'); $usuario177->setEmail($usuario177->getUsername()); $usuario177->setPlainPassword('123456');$usuario177->setEnabled(true); $usuario177->setRoles(array('ROLE_ADMIN'));$userManager->updateUser($usuario177, true);$this->addReference('usuario177', $usuario177);
        $usuario178= $userManager->createUser();$usuario178->setUsername('rolivos@imagina.cl'); $usuario178->setNombres('Rodrigo'); $usuario178->setApellidos('Olivos Toro'); $usuario178->setEmail($usuario178->getUsername()); $usuario178->setPlainPassword('123456');$usuario178->setEnabled(true); $usuario178->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario178, true);$this->addReference('usuario178', $usuario178);
        $usuario179= $userManager->createUser();$usuario179->setUsername('rprado@imagina.cl'); $usuario179->setNombres('Rodrigo'); $usuario179->setApellidos('Prado'); $usuario179->setEmail($usuario179->getUsername()); $usuario179->setPlainPassword('123456');$usuario179->setEnabled(true); $usuario179->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario179, true);$this->addReference('usuario179', $usuario179);
        $usuario180= $userManager->createUser();$usuario180->setUsername('rrivera@imagina.cl'); $usuario180->setNombres('Romina'); $usuario180->setApellidos('Rivera'); $usuario180->setEmail($usuario180->getUsername()); $usuario180->setPlainPassword('123456');$usuario180->setEnabled(true); $usuario180->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario180, true);$this->addReference('usuario180', $usuario180);
        $usuario181= $userManager->createUser();$usuario181->setUsername('rrobinson@imagina.cl'); $usuario181->setNombres('Roberto'); $usuario181->setApellidos('Robinson'); $usuario181->setEmail($usuario181->getUsername()); $usuario181->setPlainPassword('123456');$usuario181->setEnabled(true); $usuario181->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario181, true);$this->addReference('usuario181', $usuario181);
        $usuario182= $userManager->createUser();$usuario182->setUsername('rsaavedra@imagina.cl'); $usuario182->setNombres('Ruben'); $usuario182->setApellidos('Saavedra'); $usuario182->setEmail($usuario182->getUsername()); $usuario182->setPlainPassword('123456');$usuario182->setEnabled(true); $usuario182->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario182, true);$this->addReference('usuario182', $usuario182);
        $usuario183= $userManager->createUser();$usuario183->setUsername('rsalgado@imagina.cl'); $usuario183->setNombres('Roberto'); $usuario183->setApellidos('Salgado'); $usuario183->setEmail($usuario183->getUsername()); $usuario183->setPlainPassword('123456');$usuario183->setEnabled(true); $usuario183->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario183, true);$this->addReference('usuario183', $usuario183);
        $usuario184= $userManager->createUser();$usuario184->setUsername('rsuarez@imagina.cl'); $usuario184->setNombres('Rhaizy'); $usuario184->setApellidos('Suarez'); $usuario184->setEmail($usuario184->getUsername()); $usuario184->setPlainPassword('123456');$usuario184->setEnabled(true); $usuario184->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario184, true);$this->addReference('usuario184', $usuario184);
        $usuario185= $userManager->createUser();$usuario185->setUsername('rtomsich@imagina.cl'); $usuario185->setNombres('Rodrigo'); $usuario185->setApellidos('Tomsich'); $usuario185->setEmail($usuario185->getUsername()); $usuario185->setPlainPassword('123456');$usuario185->setEnabled(true); $usuario185->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario185, true);$this->addReference('usuario185', $usuario185);
        $usuario186= $userManager->createUser();$usuario186->setUsername('rtudela@imagina.cl'); $usuario186->setNombres('Rodrigo'); $usuario186->setApellidos('Tudela'); $usuario186->setEmail($usuario186->getUsername()); $usuario186->setPlainPassword('123456');$usuario186->setEnabled(true); $usuario186->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario186, true);$this->addReference('usuario186', $usuario186);
        $usuario187= $userManager->createUser();$usuario187->setUsername('rvidal@imagina.cl'); $usuario187->setNombres('Rene'); $usuario187->setApellidos('Vidal'); $usuario187->setEmail($usuario187->getUsername()); $usuario187->setPlainPassword('123456');$usuario187->setEnabled(true); $usuario187->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario187, true);$this->addReference('usuario187', $usuario187);
        $usuario188= $userManager->createUser();$usuario188->setUsername('rzambrano@imagina.cl'); $usuario188->setNombres('Rodrigo'); $usuario188->setApellidos('Zambrano'); $usuario188->setEmail($usuario188->getUsername()); $usuario188->setPlainPassword('123456');$usuario188->setEnabled(true); $usuario188->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario188, true);$this->addReference('usuario188', $usuario188);
        $usuario189= $userManager->createUser();$usuario189->setUsername('scartagena@imagina.cl'); $usuario189->setNombres('Sebastian'); $usuario189->setApellidos('Cartagena'); $usuario189->setEmail($usuario189->getUsername()); $usuario189->setPlainPassword('123456');$usuario189->setEnabled(true); $usuario189->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario189, true);$this->addReference('usuario189', $usuario189);
        $usuario190= $userManager->createUser();$usuario190->setUsername('sdelvillar@imagina.cl'); $usuario190->setNombres('Sergio'); $usuario190->setApellidos('Del Villar'); $usuario190->setEmail($usuario190->getUsername()); $usuario190->setPlainPassword('123456');$usuario190->setEnabled(true); $usuario190->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario190, true);$this->addReference('usuario190', $usuario190);
        $usuario191= $userManager->createUser();$usuario191->setUsername('slarenas@imagina.cl'); $usuario191->setNombres('Sebastian'); $usuario191->setApellidos('Larenas Gonzalez'); $usuario191->setEmail($usuario191->getUsername()); $usuario191->setPlainPassword('123456');$usuario191->setEnabled(true); $usuario191->setRoles(array('ROLE_ADMIN'));$userManager->updateUser($usuario191, true);$this->addReference('usuario191', $usuario191);
        $usuario192= $userManager->createUser();$usuario192->setUsername('smoya@imagina.cl'); $usuario192->setNombres('Susana'); $usuario192->setApellidos('Moya'); $usuario192->setEmail($usuario192->getUsername()); $usuario192->setPlainPassword('123456');$usuario192->setEnabled(true); $usuario192->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario192, true);$this->addReference('usuario192', $usuario192);
        $usuario193= $userManager->createUser();$usuario193->setUsername('sriera@imagina.cl'); $usuario193->setNombres('Sunem'); $usuario193->setApellidos('Riera'); $usuario193->setEmail($usuario193->getUsername()); $usuario193->setPlainPassword('123456');$usuario193->setEnabled(true); $usuario193->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario193, true);$this->addReference('usuario193', $usuario193);
        $usuario194= $userManager->createUser();$usuario194->setUsername('talcalde@imagina.cl'); $usuario194->setNombres('Tomas'); $usuario194->setApellidos('Alcalde Herrera'); $usuario194->setEmail($usuario194->getUsername()); $usuario194->setPlainPassword('123456');$usuario194->setEnabled(true); $usuario194->setRoles(array('ROLE_ADMIN'));$userManager->updateUser($usuario194, true);$this->addReference('usuario194', $usuario194);
        $usuario195= $userManager->createUser();$usuario195->setUsername('tavila@imagina.cl'); $usuario195->setNombres('Thais'); $usuario195->setApellidos('Avila'); $usuario195->setEmail($usuario195->getUsername()); $usuario195->setPlainPassword('123456');$usuario195->setEnabled(true); $usuario195->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario195, true);$this->addReference('usuario195', $usuario195);
        $usuario196= $userManager->createUser();$usuario196->setUsername('usubiabre@imagina.cl'); $usuario196->setNombres('Ulises'); $usuario196->setApellidos('Subiabre Imagina'); $usuario196->setEmail($usuario196->getUsername()); $usuario196->setPlainPassword('123456');$usuario196->setEnabled(true); $usuario196->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario196, true);$this->addReference('usuario196', $usuario196);
        $usuario197= $userManager->createUser();$usuario197->setUsername('vacevedo@imagina.cl'); $usuario197->setNombres('Veronica'); $usuario197->setApellidos('Acevedo'); $usuario197->setEmail($usuario197->getUsername()); $usuario197->setPlainPassword('123456');$usuario197->setEnabled(true); $usuario197->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario197, true);$this->addReference('usuario197', $usuario197);
        $usuario198= $userManager->createUser();$usuario198->setUsername('vflores@imagina.cl'); $usuario198->setNombres('Victor Hugo'); $usuario198->setApellidos('Flores'); $usuario198->setEmail($usuario198->getUsername()); $usuario198->setPlainPassword('123456');$usuario198->setEnabled(true); $usuario198->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario198, true);$this->addReference('usuario198', $usuario198);
        $usuario199= $userManager->createUser();$usuario199->setUsername('xvillegas@imagina.cl'); $usuario199->setNombres('Xiomara'); $usuario199->setApellidos('Villegas'); $usuario199->setEmail($usuario199->getUsername()); $usuario199->setPlainPassword('123456');$usuario199->setEnabled(true); $usuario199->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario199, true);$this->addReference('usuario199', $usuario199);
        $usuario200= $userManager->createUser();$usuario200->setUsername('yurdaneta@imagina.cl'); $usuario200->setNombres('Yozusi'); $usuario200->setApellidos('Urdaneta'); $usuario200->setEmail($usuario200->getUsername()); $usuario200->setPlainPassword('123456');$usuario200->setEnabled(true); $usuario200->setRoles(array('ROLE_USER'));$userManager->updateUser($usuario200, true);$this->addReference('usuario200', $usuario200);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {
        return 0;
    }
}
