<?php
namespace Option\AutoagasBundle\DataFixtures\ORM;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use AppBundle\Entity\Comuna;
use AppBundle\Entity\Region;

/**
 * Class LoadComunaData
 * @package Option\AutoagasBundle\DataFixtures\ORM
 * 
 * @author Roberto Zuñiga Araya <roberto.zuniga.araya@gmail.com>
 */
class LoadComunaData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }

    /**
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        $comunas = $this->getComunas();

        foreach ($comunas as $comuna) {
            $newComuna = new Comuna();

            $newComuna
                ->setName($comuna['name'])
                ->setRegion($this->getRegion($manager, $comuna['region']))
            ;

            $manager->persist($newComuna);
        }

        $manager->flush();

    }

    /**
     * @param ObjectManager $manager
     * @param $name
     * @return Region
     */
    public function getRegion(ObjectManager $manager, $name)
    {
        return $manager->getRepository('AppBundle:Region')->findOneBy(array('code'=>$name));
    }

    /**
     * @return array
     */
    private function getComunas()
    {

        return [
            ['name' => 'Arica',                      'region' => 'XV'],
            ['name' => 'Camarones',                  'region' => 'XV'],
            ['name' => 'General Lagos',              'region' => 'XV'],
            ['name' => 'Putre',                      'region' => 'XV'],
            ['name' => 'Alto Hospicio',              'region' => 'I'],
            ['name' => 'Iquique',                    'region' => 'I'],
            ['name' => 'Camiña',                     'region' => 'I'],
            ['name' => 'Colchane',                   'region' => 'I'],
            ['name' => 'Huara',                      'region' => 'I'],
            ['name' => 'Pica',                       'region' => 'I'],
            ['name' => 'Pozo Almonte',               'region' => 'I'],
            ['name' => 'Antofagasta',                'region' => 'II'],
            ['name' => 'Mejillones',                 'region' => 'II'],
            ['name' => 'Sierra Gorda',               'region' => 'II'],
            ['name' => 'Taltal',                     'region' => 'II'],
            ['name' => 'Calama',                     'region' => 'II'],
            ['name' => 'Ollague',                    'region' => 'II'],
            ['name' => 'San Pedro de Atacama',       'region' => 'II'],
            ['name' => 'María Elena',                'region' => 'II'],
            ['name' => 'Tocopilla',                  'region' => 'II'],
            ['name' => 'Chañaral',                   'region' => 'III'],
            ['name' => 'Diego de Almagro',           'region' => 'III'],
            ['name' => 'Caldera',                    'region' => 'III'],
            ['name' => 'Copiapó',                    'region' => 'III'],
            ['name' => 'Tierra Amarilla',            'region' => 'III'],
            ['name' => 'Alto del Carmen',            'region' => 'III'],
            ['name' => 'Freirina',                   'region' => 'III'],
            ['name' => 'Huasco',                     'region' => 'III'],
            ['name' => 'Vallenar',                   'region' => 'III'],
            ['name' => 'Canela',                     'region' => 'IV'],
            ['name' => 'Illapel',                    'region' => 'IV'],
            ['name' => 'Los Vilos',                  'region' => 'IV'],
            ['name' => 'Salamanca',                  'region' => 'IV'],
            ['name' => 'Andacollo',                  'region' => 'IV'],
            ['name' => 'Coquimbo',                   'region' => 'IV'],
            ['name' => 'La Higuera',                 'region' => 'IV'],
            ['name' => 'La Serena',                  'region' => 'IV'],
            ['name' => 'Paihuaco',                   'region' => 'IV'],
            ['name' => 'Vicuña',                     'region' => 'IV'],
            ['name' => 'Combarbalá',                 'region' => 'IV'],
            ['name' => 'Monte Patria',               'region' => 'IV'],
            ['name' => 'Ovalle',                     'region' => 'IV'],
            ['name' => 'Punitaqui',                  'region' => 'IV'],
            ['name' => 'Río Hurtado',                'region' => 'IV'],
            ['name' => 'Isla de Pascua',             'region' => 'V'],
            ['name' => 'Calle Larga',                'region' => 'V'],
            ['name' => 'Los Andes',                  'region' => 'V'],
            ['name' => 'Rinconada',                  'region' => 'V'],
            ['name' => 'San Esteban',                'region' => 'V'],
            ['name' => 'La Ligua',                   'region' => 'V'],
            ['name' => 'Papudo',                     'region' => 'V'],
            ['name' => 'Petorca',                    'region' => 'V'],
            ['name' => 'Zapallar',                   'region' => 'V'],
            ['name' => 'Hijuelas',                   'region' => 'V'],
            ['name' => 'La Calera',                  'region' => 'V'],
            ['name' => 'La Cruz',                    'region' => 'V'],
            ['name' => 'Limache',                    'region' => 'V'],
            ['name' => 'Nogales',                    'region' => 'V'],
            ['name' => 'Olmué',                      'region' => 'V'],
            ['name' => 'Quillota',                   'region' => 'V'],
            ['name' => 'Algarrobo',                  'region' => 'V'],
            ['name' => 'Cartagena',                  'region' => 'V'],
            ['name' => 'El Quisco',                  'region' => 'V'],
            ['name' => 'El Tabo',                    'region' => 'V'],
            ['name' => 'San Antonio',                'region' => 'V'],
            ['name' => 'Santo Domingo',              'region' => 'V'],
            ['name' => 'Catemu',                     'region' => 'V'],
            ['name' => 'Llaillay',                   'region' => 'V'],
            ['name' => 'Panquehue',                  'region' => 'V'],
            ['name' => 'Putaendo',                   'region' => 'V'],
            ['name' => 'San Felipe',                 'region' => 'V'],
            ['name' => 'Santa María',                'region' => 'V'],
            ['name' => 'Casablanca',                 'region' => 'V'],
            ['name' => 'Concón',                     'region' => 'V'],
            ['name' => 'Juan Fernández',             'region' => 'V'],
            ['name' => 'Puchuncaví',                 'region' => 'V'],
            ['name' => 'Quilpué',                    'region' => 'V'],
            ['name' => 'Quintero',                   'region' => 'V'],
            ['name' => 'Valparaíso',                 'region' => 'V'],
            ['name' => 'Villa Alemana',              'region' => 'V'],
            ['name' => 'Viña del Mar',               'region' => 'V'],
            ['name' => 'Colina',                     'region' => 'RM'],
            ['name' => 'Lampa',                      'region' => 'RM'],
            ['name' => 'Tiltil',                     'region' => 'RM'],
            ['name' => 'Pirque',                     'region' => 'RM'],
            ['name' => 'Puente Alto',                'region' => 'RM'],
            ['name' => 'San José de Maipo',          'region' => 'RM'],
            ['name' => 'Buin',                       'region' => 'RM'],
            ['name' => 'Calera de Tango',            'region' => 'RM'],
            ['name' => 'Paine',                      'region' => 'RM'],
            ['name' => 'San Bernardo',               'region' => 'RM'],
            ['name' => 'Alhué',                      'region' => 'RM'],
            ['name' => 'Curacaví',                   'region' => 'RM'],
            ['name' => 'María Pinto',                'region' => 'RM'],
            ['name' => 'Melipilla',                  'region' => 'RM'],
            ['name' => 'San Pedro',                  'region' => 'RM'],
            ['name' => 'Cerrillos',                  'region' => 'RM'],
            ['name' => 'Cerro Navia',                'region' => 'RM'],
            ['name' => 'Conchalí',                   'region' => 'RM'],
            ['name' => 'El Bosque',                  'region' => 'RM'],
            ['name' => 'Estación Central',           'region' => 'RM'],
            ['name' => 'Huechuraba',                 'region' => 'RM'],
            ['name' => 'Independencia',              'region' => 'RM'],
            ['name' => 'La Cisterna',                'region' => 'RM'],
            ['name' => 'La Granja',                  'region' => 'RM'],
            ['name' => 'La Florida',                 'region' => 'RM'],
            ['name' => 'La Pintana',                 'region' => 'RM'],
            ['name' => 'La Reina',                   'region' => 'RM'],
            ['name' => 'Las Condes',                 'region' => 'RM'],
            ['name' => 'Lo Barnechea',               'region' => 'RM'],
            ['name' => 'Lo Espejo',                  'region' => 'RM'],
            ['name' => 'Lo Prado',                   'region' => 'RM'],
            ['name' => 'Macul',                      'region' => 'RM'],
            ['name' => 'Maipú',                      'region' => 'RM'],
            ['name' => 'Ñuñoa',                      'region' => 'RM'],
            ['name' => 'Pedro Aguirre Cerda',        'region' => 'RM'],
            ['name' => 'Peñalolén',                  'region' => 'RM'],
            ['name' => 'Providencia',                'region' => 'RM'],
            ['name' => 'Pudahuel',                   'region' => 'RM'],
            ['name' => 'Quilicura',                  'region' => 'RM'],
            ['name' => 'Quinta Normal',              'region' => 'RM'],
            ['name' => 'Recoleta',                   'region' => 'RM'],
            ['name' => 'Renca',                      'region' => 'RM'],
            ['name' => 'San Miguel',                 'region' => 'RM'],
            ['name' => 'San Joaquín',                'region' => 'RM'],
            ['name' => 'San Ramón',                  'region' => 'RM'],
            ['name' => 'Santiago',                   'region' => 'RM'],
            ['name' => 'Vitacura',                   'region' => 'RM'],
            ['name' => 'El Monte',                   'region' => 'RM'],
            ['name' => 'Isla de Maipo',              'region' => 'RM'],
            ['name' => 'Padre Hurtado',              'region' => 'RM'],
            ['name' => 'Peñaflor',                   'region' => 'RM'],
            ['name' => 'Talagante',                  'region' => 'RM'],
            ['name' => 'Codegua',                    'region' => 'VI'],
            ['name' => 'Coínco',                     'region' => 'VI'],
            ['name' => 'Coltauco',                   'region' => 'VI'],
            ['name' => 'Doñihue',                    'region' => 'VI'],
            ['name' => 'Graneros',                   'region' => 'VI'],
            ['name' => 'Las Cabras',                 'region' => 'VI'],
            ['name' => 'Machalí',                    'region' => 'VI'],
            ['name' => 'Malloa',                     'region' => 'VI'],
            ['name' => 'Mostazal',                   'region' => 'VI'],
            ['name' => 'Olivar',                     'region' => 'VI'],
            ['name' => 'Peumo',                      'region' => 'VI'],
            ['name' => 'Pichidegua',                 'region' => 'VI'],
            ['name' => 'Quinta de Tilcoco',          'region' => 'VI'],
            ['name' => 'Rancagua',                   'region' => 'VI'],
            ['name' => 'Rengo',                      'region' => 'VI'],
            ['name' => 'Requínoa',                   'region' => 'VI'],
            ['name' => 'San Vicente de Tagua Tagua', 'region' => 'VI'],
            ['name' => 'La Estrella',                'region' => 'VI'],
            ['name' => 'Litueche',                   'region' => 'VI'],
            ['name' => 'Marchihue',                  'region' => 'VI'],
            ['name' => 'Navidad',                    'region' => 'VI'],
            ['name' => 'Peredones',                  'region' => 'VI'],
            ['name' => 'Pichilemu',                  'region' => 'VI'],
            ['name' => 'Chépica',                    'region' => 'VI'],
            ['name' => 'Chimbarongo',                'region' => 'VI'],
            ['name' => 'Lolol',                      'region' => 'VI'],
            ['name' => 'Nancagua',                   'region' => 'VI'],
            ['name' => 'Palmilla',                   'region' => 'VI'],
            ['name' => 'Peralillo',                  'region' => 'VI'],
            ['name' => 'Placilla',                   'region' => 'VI'],
            ['name' => 'Pumanque',                   'region' => 'VI'],
            ['name' => 'San Fernando',               'region' => 'VI'],
            ['name' => 'Santa Cruz',                 'region' => 'VI'],
            ['name' => 'Cauquenes',                  'region' => 'VII'],
            ['name' => 'Chanco',                     'region' => 'VII'],
            ['name' => 'Pelluhue',                   'region' => 'VII'],
            ['name' => 'Curicó',                     'region' => 'VII'],
            ['name' => 'Hualañé',                    'region' => 'VII'],
            ['name' => 'Licantén',                   'region' => 'VII'],
            ['name' => 'Molina',                     'region' => 'VII'],
            ['name' => 'Rauco',                      'region' => 'VII'],
            ['name' => 'Romeral',                    'region' => 'VII'],
            ['name' => 'Sagrada Familia',            'region' => 'VII'],
            ['name' => 'Teno',                       'region' => 'VII'],
            ['name' => 'Vichuquén',                  'region' => 'VII'],
            ['name' => 'Colbún',                     'region' => 'VII'],
            ['name' => 'Linares',                    'region' => 'VII'],
            ['name' => 'Longaví',                    'region' => 'VII'],
            ['name' => 'Parral',                     'region' => 'VII'],
            ['name' => 'Retiro',                     'region' => 'VII'],
            ['name' => 'San Javier',                 'region' => 'VII'],
            ['name' => 'Villa Alegre',               'region' => 'VII'],
            ['name' => 'Yerbas Buenas',              'region' => 'VII'],
            ['name' => 'Constitución',               'region' => 'VII'],
            ['name' => 'Curepto',                    'region' => 'VII'],
            ['name' => 'Empedrado',                  'region' => 'VII'],
            ['name' => 'Maule',                      'region' => 'VII'],
            ['name' => 'Pelarco',                    'region' => 'VII'],
            ['name' => 'Pencahue',                   'region' => 'VII'],
            ['name' => 'Río Claro',                  'region' => 'VII'],
            ['name' => 'San Clemente',               'region' => 'VII'],
            ['name' => 'San Rafael',                 'region' => 'VII'],
            ['name' => 'Talca',                      'region' => 'VII'],
            ['name' => 'Arauco',                     'region' => 'VIII'],
            ['name' => 'Cañete',                     'region' => 'VIII'],
            ['name' => 'Contulmo',                   'region' => 'VIII'],
            ['name' => 'Curanilahue',                'region' => 'VIII'],
            ['name' => 'Lebu',                       'region' => 'VIII'],
            ['name' => 'Los Álamos',                 'region' => 'VIII'],
            ['name' => 'Tirúa',                      'region' => 'VIII'],
            ['name' => 'Alto Biobío',                'region' => 'VIII'],
            ['name' => 'Antuco',                     'region' => 'VIII'],
            ['name' => 'Cabrero',                    'region' => 'VIII'],
            ['name' => 'Laja',                       'region' => 'VIII'],
            ['name' => 'Los Ángeles',                'region' => 'VIII'],
            ['name' => 'Mulchén',                    'region' => 'VIII'],
            ['name' => 'Nacimiento',                 'region' => 'VIII'],
            ['name' => 'Negrete',                    'region' => 'VIII'],
            ['name' => 'Quilaco',                    'region' => 'VIII'],
            ['name' => 'Quilleco',                   'region' => 'VIII'],
            ['name' => 'San Rosendo',                'region' => 'VIII'],
            ['name' => 'Santa Bárbara',              'region' => 'VIII'],
            ['name' => 'Tucapel',                    'region' => 'VIII'],
            ['name' => 'Yumbel',                     'region' => 'VIII'],
            ['name' => 'Chiguayante',                'region' => 'VIII'],
            ['name' => 'Concepción',                 'region' => 'VIII'],
            ['name' => 'Coronel',                    'region' => 'VIII'],
            ['name' => 'Florida',                    'region' => 'VIII'],
            ['name' => 'Hualpén',                    'region' => 'VIII'],
            ['name' => 'Hualqui',                    'region' => 'VIII'],
            ['name' => 'Lota',                       'region' => 'VIII'],
            ['name' => 'Penco',                      'region' => 'VIII'],
            ['name' => 'San Pedro de La Paz',        'region' => 'VIII'],
            ['name' => 'Santa Juana',                'region' => 'VIII'],
            ['name' => 'Talcahuano',                 'region' => 'VIII'],
            ['name' => 'Tomé',                       'region' => 'VIII'],
            ['name' => 'Bulnes',                     'region' => 'VIII'],
            ['name' => 'Chillán',                    'region' => 'VIII'],
            ['name' => 'Chillán Viejo',              'region' => 'VIII'],
            ['name' => 'Cobquecura',                 'region' => 'VIII'],
            ['name' => 'Coelemu',                    'region' => 'VIII'],
            ['name' => 'Coihueco',                   'region' => 'VIII'],
            ['name' => 'El Carmen',                  'region' => 'VIII'],
            ['name' => 'Ninhue',                     'region' => 'VIII'],
            ['name' => 'Ñiquen',                     'region' => 'VIII'],
            ['name' => 'Pemuco',                     'region' => 'VIII'],
            ['name' => 'Pinto',                      'region' => 'VIII'],
            ['name' => 'Portezuelo',                 'region' => 'VIII'],
            ['name' => 'Quillón',                    'region' => 'VIII'],
            ['name' => 'Quirihue',                   'region' => 'VIII'],
            ['name' => 'Ránquil',                    'region' => 'VIII'],
            ['name' => 'San Carlos',                 'region' => 'VIII'],
            ['name' => 'San Fabián',                 'region' => 'VIII'],
            ['name' => 'San Ignacio',                'region' => 'VIII'],
            ['name' => 'San Nicolás',                'region' => 'VIII'],
            ['name' => 'Treguaco',                   'region' => 'VIII'],
            ['name' => 'Yungay',                     'region' => 'VIII'],
            ['name' => 'Carahue',                    'region' => 'IX'],
            ['name' => 'Cholchol',                   'region' => 'IX'],
            ['name' => 'Cunco',                      'region' => 'IX'],
            ['name' => 'Curarrehue',                 'region' => 'IX'],
            ['name' => 'Freire',                     'region' => 'IX'],
            ['name' => 'Galvarino',                  'region' => 'IX'],
            ['name' => 'Gorbea',                     'region' => 'IX'],
            ['name' => 'Lautaro',                    'region' => 'IX'],
            ['name' => 'Loncoche',                   'region' => 'IX'],
            ['name' => 'Melipeuco',                  'region' => 'IX'],
            ['name' => 'Nueva Imperial',             'region' => 'IX'],
            ['name' => 'Padre Las Casas',            'region' => 'IX'],
            ['name' => 'Perquenco',                  'region' => 'IX'],
            ['name' => 'Pitrufquén',                 'region' => 'IX'],
            ['name' => 'Pucón',                      'region' => 'IX'],
            ['name' => 'Saavedra',                   'region' => 'IX'],
            ['name' => 'Temuco',                     'region' => 'IX'],
            ['name' => 'Teodoro Schmidt',            'region' => 'IX'],
            ['name' => 'Toltén',                     'region' => 'IX'],
            ['name' => 'Vilcún',                     'region' => 'IX'],
            ['name' => 'Villarrica',                 'region' => 'IX'],
            ['name' => 'Angol',                      'region' => 'IX'],
            ['name' => 'Collipulli',                 'region' => 'IX'],
            ['name' => 'Curacautín',                 'region' => 'IX'],
            ['name' => 'Ercilla',                    'region' => 'IX'],
            ['name' => 'Lonquimay',                  'region' => 'IX'],
            ['name' => 'Los Sauces',                 'region' => 'IX'],
            ['name' => 'Lumaco',                     'region' => 'IX'],
            ['name' => 'Purén',                      'region' => 'IX'],
            ['name' => 'Renaico',                    'region' => 'IX'],
            ['name' => 'Traiguén',                   'region' => 'IX'],
            ['name' => 'Victoria',                   'region' => 'IX'],
            ['name' => 'Corral',                     'region' => 'XIV'],
            ['name' => 'Lanco',                      'region' => 'XIV'],
            ['name' => 'Los Lagos',                  'region' => 'XIV'],
            ['name' => 'Máfil',                      'region' => 'XIV'],
            ['name' => 'Mariquina',                  'region' => 'XIV'],
            ['name' => 'Paillaco',                   'region' => 'XIV'],
            ['name' => 'Panguipulli',                'region' => 'XIV'],
            ['name' => 'Valdivia',                   'region' => 'XIV'],
            ['name' => 'Futrono',                    'region' => 'XIV'],
            ['name' => 'La Unión',                   'region' => 'XIV'],
            ['name' => 'Lago Ranco',                 'region' => 'XIV'],
            ['name' => 'Río Bueno',                  'region' => 'XIV'],
            ['name' => 'Ancud',                      'region' => 'X'],
            ['name' => 'Castro',                     'region' => 'X'],
            ['name' => 'Chonchi',                    'region' => 'X'],
            ['name' => 'Curaco de Vélez',            'region' => 'X'],
            ['name' => 'Dalcahue',                   'region' => 'X'],
            ['name' => 'Puqueldón',                  'region' => 'X'],
            ['name' => 'Queilén',                    'region' => 'X'],
            ['name' => 'Quemchi',                    'region' => 'X'],
            ['name' => 'Quellón',                    'region' => 'X'],
            ['name' => 'Quinchao',                   'region' => 'X'],
            ['name' => 'Calbuco',                    'region' => 'X'],
            ['name' => 'Cochamó',                    'region' => 'X'],
            ['name' => 'Fresia',                     'region' => 'X'],
            ['name' => 'Frutillar',                  'region' => 'X'],
            ['name' => 'Llanquihue',                 'region' => 'X'],
            ['name' => 'Los Muermos',                'region' => 'X'],
            ['name' => 'Maullín',                    'region' => 'X'],
            ['name' => 'Puerto Montt',               'region' => 'X'],
            ['name' => 'Puerto Varas',               'region' => 'X'],
            ['name' => 'Osorno',                     'region' => 'X'],
            ['name' => 'Puero Octay',                'region' => 'X'],
            ['name' => 'Purranque',                  'region' => 'X'],
            ['name' => 'Puyehue',                    'region' => 'X'],
            ['name' => 'Río Negro',                  'region' => 'X'],
            ['name' => 'San Juan de la Costa',       'region' => 'X'],
            ['name' => 'San Pablo',                  'region' => 'X'],
            ['name' => 'Chaitén',                    'region' => 'X'],
            ['name' => 'Futaleufú',                  'region' => 'X'],
            ['name' => 'Hualaihué',                  'region' => 'X'],
            ['name' => 'Palena',                     'region' => 'X'],
            ['name' => 'Aisén',                      'region' => 'XI'],
            ['name' => 'Cisnes',                     'region' => 'XI'],
            ['name' => 'Guaitecas',                  'region' => 'XI'],
            ['name' => 'Cochrane',                   'region' => 'XI'],
            ['name' => 'O\'higgins',                 'region' => 'XI'],
            ['name' => 'Tortel',                     'region' => 'XI'],
            ['name' => 'Coihaique',                  'region' => 'XI'],
            ['name' => 'Lago Verde',                 'region' => 'XI'],
            ['name' => 'Chile Chico',                'region' => 'XI'],
            ['name' => 'Río Ibáñez',                 'region' => 'XI'],
            ['name' => 'Antártica',                  'region' => 'XII'],
            ['name' => 'Cabo de Hornos',             'region' => 'XII'],
            ['name' => 'Laguna Blanca',              'region' => 'XII'],
            ['name' => 'Punta Arenas',               'region' => 'XII'],
            ['name' => 'Río Verde',                  'region' => 'XII'],
            ['name' => 'San Gregorio',               'region' => 'XII'],
            ['name' => 'Porvenir',                   'region' => 'XII'],
            ['name' => 'Primavera',                  'region' => 'XII'],
            ['name' => 'Timaukel',                   'region' => 'XII'],
            ['name' => 'Natales',                    'region' => 'XII'],
            ['name' => 'Torres del Paine',           'region' => 'XII'],
        ];
    }
}